# Generated by Django 5.1.15 on 2026-09-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('key', models.SlugField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sectors', models.JSONField(blank=True, default=list, verbose_name='setores')),
                ('modules', models.JSONField(blank=True, default=list, verbose_name='módulos')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='access_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.accessprofile'),
        ),
        migrations.AddConstraint(
            model_name='accessprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_access_profile_key'),
        ),
    ]
