# Generated by Django 5.1.15 on 2026-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_modulo_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='município'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='razão social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
