# Generated by Django 5.1.15 on 2026-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dados_da_empresa_e_departamento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_tenants',
            field=models.ManyToManyField(blank=True, related_name='guest_users', to='accounts.tenant', verbose_name='outras empresas'),
        ),
    ]
