# Generated by Django 5.1.15 on 2026-09-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vinculo_com_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.tenant', verbose_name='empresa principal'),
        ),
    ]
