"""Catálogo de KPIs do WinThor — o que a empresa pluga com um clique.

Fonte: estudos do extrator (Recife Doces, Nordeste Boi, MakFrios) sobre o
schema e o PL/SQL do WinThor mais o SQL capturado em runtime. Cada item cita
a regra real do ERP (`rule`): tabela, coluna, rotina ou package. Quando a
métrica já existe no espelho (`erp_metric`), o KPI nasce calculado; quando
depende de tabela ainda fora do plano de coleta, vai como `planejado` com a
lista `requer` — aparece no catálogo, mas não pluga até a coleta existir.

Semeado em `KpiTemplate` por `manage.py seed_kpi_winthor` (idempotente).
"""

V, C, F, E, K, L, X, R = "vendas", "clientes", "financeiro", "estoque", "compras", "logistica", "fiscal", "rh"
PF, PC, PP, PA = "financeira", "clientes", "processos", "aprendizado"
DIR = "diretoria"  # tag: entra no resumo executivo


def kpi(code, name, sector, perspective, metric="", target="", *, rule="", desc="", tags=(), filters=None,
        requer=(), unit=None, polarity=None, aggregation=None, decimals=None):
    """`unit/polarity/aggregation/decimals` vêm da métrica quando existe; aqui só sobrescrevem."""
    return {
        "code": code, "name": name, "sector": sector, "perspective": perspective,
        "erp_metric": metric, "erp_target": target, "rule": rule, "description": desc,
        "tags": list(tags), "default_filters": filters or {}, "requer": list(requer),
        "unit": unit, "polarity": polarity, "aggregation": aggregation, "decimals": decimals,
    }


CATALOGO = [
    # ------------------------------------------------------------------ VENDAS
    kpi("FAT", "Faturamento líquido", V, PF, "faturamento", "vlvendaprev", tags=[DIR],
        rule="PCNFSAID: soma de VLTOTAL das notas de saída não canceladas (DTCANCEL nula), fora CONDVENDA 4/8/10/13/20/98/99 e bonificação 5/6/11/12 — a mesma régua da view SQL_INTEGRACAO_NF_VENDAS. Meta: PCMETARCA (meta diária por RCA) ou PCUSUARI.VLVENDAPREV.",
        desc="O que a empresa faturou de fato. É o número de referência de todos os demais."),
    kpi("FAT_YOY", "Crescimento do faturamento (ano a ano)", V, PF, "crescimento_faturamento_yoy_pct", tags=[DIR],
        rule="Faturamento do período ÷ faturamento do mesmo período do ano anterior (PCNFSAID.DTSAIDA).",
        desc="Se a empresa está crescendo ou encolhendo em relação ao ano passado."),
    kpi("NOTAS", "Notas emitidas", V, PP, "qtd_notas",
        rule="Contagem de PCNFSAID faturadas (mesma régua do faturamento).", desc="Volume de vendas em documentos."),
    kpi("TKT", "Ticket médio", V, PC, "ticket_medio", "vlmediopedido",
        rule="Faturamento ÷ notas. Meta em PCMETA.VLMEDIOPEDIDO quando a rotina 3305 é usada.",
        desc="Quanto cada venda carrega em média."),
    kpi("POSIT", "Clientes positivados", V, PC, "positivacao", "clipos", tags=[DIR],
        rule="Clientes distintos com nota faturada no mês — a apuração da rotina 111 (QTPOSITIVACAOFATURADOS). Meta: PCMETARCA.NUMCLIPOS ou PCMETA.CLIPOSPREV.",
        desc="Quantos clientes compraram no mês."),
    kpi("POS_RCA", "Clientes positivados por RCA", V, PC, "clientes_por_rca",
        rule="Positivação ÷ RCAs com venda (PCNFSAID.CODUSUR).", desc="Cobertura média da carteira por vendedor."),
    kpi("RCAS", "RCAs com venda", V, PP, "rcas_ativos",
        rule="CODUSUR distintos com nota faturada no mês.", desc="Quantos vendedores produziram."),
    kpi("VENDA_RCA", "Venda média por RCA", V, PF, "venda_media_por_rca",
        rule="Faturamento ÷ RCAs com venda.", desc="Produtividade média da equipe de vendas."),
    kpi("PEDIDOS", "Pedidos digitados", V, PP, "qtd_pedidos", "pedidosprev",
        rule="PCPEDC por DATA, excluindo POSICAO C. Meta: PCMETARCA.QTPEDPREV.", desc="Entrada de pedidos, antes de faturar."),
    kpi("PED_MEDIO", "Pedido médio", V, PC, "pedido_medio",
        rule="PCPEDC.VLTOTAL médio dos pedidos não cancelados.", desc="Tamanho médio do pedido digitado."),
    kpi("PED_CANC", "Pedidos cancelados", V, PP, "pedidos_cancelados_pct",
        rule="PCPEDC.POSICAO = C sobre os pedidos do período.", desc="Quanto do que foi digitado morreu antes de faturar."),
    kpi("CONV", "Conversão pedido → nota", V, PP, "conversao_pedido_nota_pct",
        rule="Pedidos com POSICAO F (DTFAT preenchida) sobre os digitados no mês.", desc="Eficiência do funil pedido → faturamento."),
    kpi("CARTEIRA", "Carteira de pedidos", V, PF, "carteira_pedidos",
        rule="PCPEDC pendentes (POSICAO L/M/B/P) — o que ainda vai faturar.", desc="Venda já vendida e ainda não faturada."),
    kpi("MIX", "Mix de produtos vendidos", V, PC, "mix_skus",
        rule="CODPROD distintos em PCMOV de venda no mês. Meta possível em PCMETA.MIXPREV.", desc="Amplitude do portfólio que gira."),
    kpi("ITENS_NOTA", "Itens por nota", V, PC, "itens_por_nota",
        rule="Linhas de PCMOV (operações de venda) ÷ notas faturadas.", desc="Profundidade média da compra do cliente."),
    kpi("FREQ", "Frequência de compra", V, PC, "notas_por_cliente",
        rule="Notas ÷ clientes positivados.", desc="Quantas vezes o cliente compra no mês."),
    kpi("DESC", "Desconto médio praticado", V, PF, "desconto_medio_pct",
        rule="PCMOV: 1 − PUNIT/PTABELA ponderado por quantidade. Limite oficial = menor entre PERMAXDESCVENDA (filial) e PCTABPR.PERDESCMAX.",
        desc="Quanto de preço a equipe cede em média."),
    kpi("BONIF", "Bonificação sobre faturamento", V, PF, "bonificacao_pct",
        rule="Notas CONDVENDA 5/6/11/12 (VLBONIFIC) sobre o faturamento.", desc="Custo comercial de brindes e bonificações."),
    kpi("DEVOL", "Devoluções sobre vendas", V, PC, "devolucoes_pct",
        rule="PCMOV operações E1/ED/EL sobre as de venda. No ERP a devolução é PCNFENT.TIPODESCARGA 6/7 ligada à venda por PCESTCOM.NUMTRANSVENDA.",
        desc="Quanto do que foi vendido voltou."),
    kpi("CORTE", "Pedidos com corte", V, PP, "corte_pct",
        rule="PCPEDC com PCPEDI.QTFALTA > 0 (falta de estoque na separação). A autoria do corte fica em PCCORTEFV.",
        desc="Pedidos entregues a menos por falta."),
    kpi("QT_CORTE", "Quantidade cortada nos pedidos", V, PP, "venda_perdida_corte",
        rule="Soma de PCPEDI.QTFALTA nos pedidos do período; a falta na importação vira PCFALTA.",
        desc="Volume de venda perdida por ruptura."),
    kpi("TOP10_CLI", "Concentração nos 10 maiores clientes", V, PC, "concentracao_top10_clientes_pct",
        rule="Fatia do faturamento dos 10 maiores CODCLI do período.", desc="Risco de dependência de poucos clientes."),
    kpi("TOP_RCA", "Dependência do maior RCA", V, PP, "concentracao_top_rca_pct",
        rule="Fatia do faturamento do CODUSUR que mais vende.", desc="Risco de concentração na equipe."),
    kpi("PRECO_MEDIO", "Preço médio por unidade", V, PF, "preco_medio_item",
        rule="PCMOV: valor vendido ÷ quantidade.", desc="Sinal de mix e de política de preço."),
    kpi("FILA_BLOQ", "Pedidos bloqueados aguardando liberação", V, PP, requer=["PCBLOQUEIOSPEDIDO", "PCMOTBLOQUEIO"],
        rule="PCBLOQUEIOSPEDIDO STATUS = B por motivo (PKG_MOTIVOBLOQUEIO, 26 regras); a liberação pela Integradora apaga a linha, só a rotina 336 marca L.",
        desc="Valor parado em bloqueio comercial/financeiro.", unit="R$", polarity="menor_melhor", aggregation="ultimo"),
    kpi("TEMPO_FILA", "Tempo médio em fila de bloqueio", V, PP, requer=["PCLOGBLOQUEIOPEDVENDA"],
        rule="PCLOGBLOQUEIOPEDVENDA (TRG_PCPEDC) dá a linha do tempo de cada bloqueio.",
        desc="Quanto o pedido espera até ser liberado.", unit="h", polarity="menor_melhor", aggregation="media", decimals=1),
    kpi("CORTE_WMS", "Corte na separação (WMS)", V, PP, requer=["PCWMSCORTE", "PCCORTEI"],
        rule="WMS_PROCESSACORTE grava PCWMSCORTE/PCCORTEI com produto, motivo e funcionário.",
        desc="Valor cortado na separação, por motivo.", unit="R$", polarity="menor_melhor", aggregation="soma"),
    kpi("FLEX_RCA", "RCAs com flex negativo", V, PF, requer=["PCUSUARI.VLCORRENTE", "PCUSUARI.VLLIMCRED"],
        rule="PC_PKG_CONTROLARSALDORCA: saldo flex em PCUSUARI.VLCORRENTE contra VLLIMCRED.",
        desc="Vendedores que estouraram a conta-corrente de desconto.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),

    # ---------------------------------------------------------------- CLIENTES
    kpi("BASE", "Base de clientes", C, PC, "base_clientes",
        rule="PCCLIENT não bloqueados e não excluídos.", desc="Tamanho da carteira cadastrada."),
    kpi("ATIVOS", "Clientes ativos (90 dias)", C, PC, "clientes_ativos", tags=[DIR],
        rule="PCCLIENT.DTULTCOMP nos últimos 90 dias.", desc="Carteira que de fato compra."),
    kpi("NCLI", "Novos clientes", C, PC, "novos_clientes",
        rule="PCCLIENT.DTPRIMCOMPRA no período (primeira compra).", desc="Conquista de clientes."),
    kpi("CADASTROS", "Clientes cadastrados no mês", C, PC, "clientes_cadastrados",
        rule="PCCLIENT.DTCADASTRO no período.", desc="Prospecção que virou cadastro."),
    kpi("CHURN", "Churn de clientes", C, PC, "churn_clientes_pct", tags=[DIR],
        rule="Clientes que compraram no trimestre anterior e não compraram no corrente (PCNFSAID).",
        desc="Perda de clientes ativos."),
    kpi("INATIVOS", "Clientes inativos (+90 dias)", C, PC, "clientes_inativos_90_pct",
        rule="PCCLIENT.DTULTCOMP há mais de 90 dias. O ERP rebaixa a classe em PRC_MED_CLASSEVENDA_CLIENTE (180 dias).",
        desc="Carteira adormecida para reativação."),
    kpi("BLOQ_CLI", "Clientes bloqueados", C, PC, "clientes_bloqueados_pct",
        rule="PCCLIENT.BLOQUEIO = S (bloqueio automático por título vencido: F_PCPREST_VENCIDA_BLOQUEIO, PCCOB.BLOQAUTOMATICO).",
        desc="Quanto da carteira está travada para vender."),
    kpi("COBERTURA", "Cobertura da base", C, PC, "positivacao_pct_base",
        rule="Positivados ÷ base ativa de 90 dias.", desc="Quanto da carteira ativa foi atendida no mês."),
    kpi("RECOMPRA", "Recompra", C, PC, "recompra_pct",
        rule="Positivados que já eram clientes (DTPRIMCOMPRA anterior ao período).", desc="Fidelidade da base."),
    kpi("CREDITO", "Crédito disponível na carteira", C, PF, requer=["PCLIMCRED", "PCCOB.VALIDALIMITECREDITO"],
        rule="PKG_LIMITECREDITO.RETORNA_LIMITE_CRED_DISPONIVEL: LIMCRED + extra + sazonal − CR aberto − pedidos a faturar − cheques.",
        desc="Espaço de crédito que a carteira ainda tem.", unit="R$", polarity="maior_melhor", aggregation="ultimo"),
    kpi("CASHBACK", "Cashback a expirar", C, PC, requer=["PCCRECLI"],
        rule="PCCRECLI.CASHBACK = S com DTVALIDADECASHBACK próxima; PRC_INT_C5_BAIXACREDEXP cancela no vencimento.",
        desc="Crédito de cliente que vai vencer sem uso.", unit="R$", polarity="menor_melhor", aggregation="ultimo"),

    # -------------------------------------------------------------- FINANCEIRO
    kpi("MARGEM", "Margem bruta", F, PF, "margem_bruta_pct", "margemprev", tags=[DIR],
        rule="PCMOV: (venda − CUSTOFIN) ÷ venda. Qual custo vale é parâmetro (CON_SUGVENDA; ORIGEMCUSTOATUFAT define a filial). Meta: PCMETA.MARGEMPREV / PCFINANC.MARGEMPREV.",
        desc="Quanto sobra da venda depois do custo da mercadoria."),
    kpi("LUCRO", "Lucro bruto", F, PF, "lucro_bruto", tags=[DIR],
        rule="Venda − custo financeiro nos itens faturados (PCMOV).", desc="Margem em reais."),
    kpi("MARKUP", "Markup", F, PF, "markup_pct",
        rule="(venda − custo) ÷ custo nos itens faturados.", desc="Quanto se acrescenta sobre o custo."),
    kpi("CMV", "CMV", F, PF, "cmv",
        rule="PCMOV.CUSTOFIN × QT nas operações de venda — o CMV gerencial de PKG_ESTOQUE.PRIV_ATUALIZAR_CUSTO.",
        desc="Custo da mercadoria vendida."),
    kpi("DESP", "Despesas por competência", F, PF, "despesas_competencia",
        rule="PCLANC não canceladas por DTCOMPETENCIA (visão de DRE).", desc="Gasto do mês, pago ou não."),
    kpi("DESP_PCT", "Despesas sobre faturamento", F, PF, "despesas_pct_faturamento", tags=[DIR],
        rule="Despesas por competência ÷ faturamento.", desc="Peso da estrutura sobre a venda."),
    kpi("FOLHA", "Folha sobre faturamento", F, PF, "folha_pct_faturamento",
        rule="PCLANC.TIPOSERVICO = 30 (salários) por competência ÷ faturamento.", desc="Custo de pessoal relativo."),
    kpi("RESULT", "Resultado operacional (aprox.)", F, PF, "resultado_operacional", tags=[DIR],
        rule="Lucro bruto − despesas por competência.", desc="Aproximação do resultado antes de impostos e financeiro."),
    kpi("RESULT_PCT", "Margem operacional (aprox.)", F, PF, "resultado_operacional_pct", tags=[DIR],
        rule="Resultado operacional ÷ faturamento.", desc="Quanto da venda vira resultado."),
    kpi("RECEB", "Recebimentos", F, PF, "recebido",
        rule="PCPREST.DTPAG no mês (VPAGO).", desc="Dinheiro que entrou de clientes."),
    kpi("PAGOS", "Pagamentos", F, PF, "despesas_pagas",
        rule="PCLANC.DTPAGTO no mês (VPAGO).", desc="Dinheiro que saiu para fornecedores e despesas."),
    kpi("ENTR_CX", "Entradas de caixa", F, PF, "entradas_caixa",
        rule="PCMOVCR TIPO = D (créditos) sem estorno.", desc="Entradas reais no extrato."),
    kpi("SAIDA_CX", "Saídas de caixa", F, PF, "saidas_caixa",
        rule="PCMOVCR TIPO = C (débitos) sem estorno.", desc="Saídas reais no extrato."),
    kpi("GERCX", "Geração de caixa", F, PF, "geracao_caixa", tags=[DIR],
        rule="Entradas − saídas do extrato (PCMOVCR).", desc="Caixa gerado no período."),
    kpi("CAIXA", "Saldo de caixa e bancos", F, PF, "saldo_caixa", tags=[DIR],
        rule="PCFINANC: SALDOCX + SALDOBCO + SALDOAPLI da última fotografia (ATUALIZACAO_DIARIA); fallback PCESTCR.",
        desc="Disponibilidade financeira do dia."),
    kpi("POSLIQ", "Posição líquida (SALDOREAL)", F, PF, "posicao_liquida_financeira",
        rule="PCFINANC.SALDOREAL: caixa + bancos + a receber − a pagar, fotografado pelo fechamento diário.",
        desc="O boletim financeiro da rotina 117 em um número."),
    kpi("CR", "Contas a receber em aberto", F, PF, "a_receber_aberto",
        rule="PCPREST com DTPAG e DTCANCEL nulas (índice canônico PCPREST_IDX83).", desc="Quanto os clientes devem."),
    kpi("CR_VENC", "A receber vencido", F, PF, "a_receber_vencido", tags=[DIR],
        rule="PCPREST em aberto com DTVENC anterior à data. O ERP conta atraso em DIAS FINANCEIROS (F_QTDIASVENCIDOS, PCDIASUTEIS).",
        desc="Carteira atrasada."),
    kpi("INAD", "Inadimplência (+30 dias)", F, PF, "inadimplencia_pct", tags=[DIR],
        rule="Vencido há mais de 30 dias ÷ total em aberto. Meta possível em PCMETA.PERINADIMPPREV.", desc="Parcela da carteira em risco."),
    kpi("CR60", "Carteira vencida há +60 dias", F, PF, "a_receber_vencido_60_pct",
        rule="Vencido há mais de 60 dias ÷ total em aberto.", desc="Envelhecimento da carteira."),
    kpi("PMR", "Prazo médio de recebimento", F, PF, "prazo_medio_recebimento",
        rule="DTPAG − DTEMISSAO ponderado por valor nos títulos pagos. Meta possível em PCMETA.PRAZOMEDIOPREV.", desc="Dias que o dinheiro leva para entrar."),
    kpi("DSO", "DSO (dias de venda em aberto)", F, PF, "dso_dias",
        rule="A receber em aberto ÷ faturamento dos últimos 90 dias × 90.", desc="Quantos dias de venda estão na rua."),
    kpi("NOPRAZO", "Títulos pagos no prazo", F, PC, "titulos_pagos_no_prazo_pct",
        rule="DTPAG ≤ DTVENC nos títulos baixados no mês.", desc="Disciplina de pagamento da carteira."),
    kpi("ATRASO", "Atraso médio dos recebimentos", F, PF, "atraso_medio_recebimento_dias",
        rule="DTPAG − DTVENC nos títulos pagos com atraso, ponderado por valor.", desc="Quanto o atrasado atrasa."),
    kpi("MULTA", "Multa e juros recebidos", F, PF, "multa_juros_recebidos",
        rule="PCPREST.VALORMULTA nas baixas do mês; o detalhe fica em PCRECEBIMENTOJUROSDESCONTO.", desc="Receita financeira de cobrança."),
    kpi("CR30", "A receber nos próximos 30 dias", F, PF, "a_receber_proximos_30_dias",
        rule="PCPREST em aberto com DTVENC nos 30 dias seguintes.", desc="Entrada prevista de curto prazo."),
    kpi("CP", "Contas a pagar em aberto", F, PF, "a_pagar_aberto",
        rule="PCLANC com DTPAGTO e DTCANCEL nulas e LANCEXCLUIDO = N (VIEW_CONTAS_A_PAGAR).", desc="Compromissos assumidos."),
    kpi("CP_VENC", "A pagar vencido", F, PF, "a_pagar_vencido",
        rule="PCLANC em aberto com DTVENC anterior à data.", desc="Compromissos atrasados."),
    kpi("CP_VENC_PCT", "Contas a pagar vencidas", F, PF, "a_pagar_vencido_pct",
        rule="Vencido ÷ total a pagar em aberto.", desc="Saúde do contas a pagar."),
    kpi("CP30", "A pagar nos próximos 30 dias", F, PF, "a_pagar_proximos_30_dias",
        rule="PCLANC em aberto com DTVENC nos 30 dias seguintes.", desc="Saída prevista de curto prazo."),
    kpi("PMP", "Prazo médio de pagamento", F, PF, "prazo_medio_pagamento",
        rule="DTPAGTO − DTEMISSAO ponderado por valor nas contas a pagar baixadas.", desc="Prazo que a empresa obtém dos fornecedores."),
    kpi("LIQ", "Liquidez (CR ÷ CP)", F, PF, "liquidez_cr_cp",
        rule="A receber em aberto ÷ a pagar em aberto.", desc="Cobertura dos compromissos pelos recebíveis."),
    kpi("BLOQ_IMIN", "Clientes com bloqueio iminente", F, PC, requer=["PCDIASUTEIS", "PCCOB"],
        rule="Régua de ATUALIZACAO_DIARIA/P_PC_BLOQUEARCLIENTE: título vencido + carência (PCCOB.NUMDIASBLOQAUTOMATIC, DIASCARENCIA) em dias financeiros.",
        desc="Clientes que o job noturno vai bloquear.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("PRORROG", "Títulos prorrogados", F, PF, requer=["PCPREST.DTVENCANTERIOR", "PCDESDLANC"],
        rule="PCPREST.DTVENCANTERIOR preenchida e cadeias de desdobramento em PCDESDLANC.",
        desc="Dias ganhos por prorrogação, por cliente/operador.", unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),
    kpi("DESC_BAIXA", "Desconto concedido na baixa", F, PF, requer=["PCRECEBIMENTOJUROSDESCONTO"],
        rule="PCRECEBIMENTOJUROSDESCONTO.VALORDESC por operador (PKG_FINANCEIRO).",
        desc="Receita cedida no ato do recebimento.", unit="R$", polarity="menor_melhor", aggregation="soma"),
    kpi("DUPLA_ASSIN", "Títulos a pagar sem dupla autorização", F, PP, requer=["PCLANC.CODFUNCAUTOR1", "PCLANC.CODFUNCAUTOR2"],
        rule="PCLANC com CODFUNCAUTOR1/2 vazios e DTVENC próxima.",
        desc="Pagamentos que vão vencer sem alçada completa.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("ADIANT_FORN", "Adiantamentos a fornecedor em aberto", F, PF, requer=["PCLANC.ADIANTAMENTO", "PCLANC.VLRUTILIZADOADIANTFORNEC"],
        rule="PCLANC.ADIANTAMENTO − VLRUTILIZADOADIANTFORNEC.",
        desc="Dinheiro adiantado e ainda não consumido.", unit="R$", polarity="menor_melhor", aggregation="ultimo"),

    # ----------------------------------------------------------------- ESTOQUE
    kpi("ESTQ", "Estoque a custo", E, PF, "estoque_valor", tags=[DIR],
        rule="PCEST.QTESTGER × CUSTOREAL (custo médio por filial; VLCUSTOREAL não existe na PCEST).", desc="Capital imobilizado em mercadoria."),
    kpi("ESTQ_FIN", "Estoque financeiro (PCFINANC)", E, PF, "estoque_financeiro_foto",
        rule="PCFINANC.SALDOESTFIN da fotografia diária.", desc="O estoque como o financeiro enxerga."),
    kpi("COBERT", "Cobertura de estoque", E, PP, "cobertura_estoque_dias", tags=[DIR],
        rule="Disponível ÷ PCEST.QTGIRODIA (giro oficial de VENDAS.CALCULARGIRODIA), ponderado por custo. Alvo por item em PCEST.ESTIDEAL.",
        desc="Dias de venda que o estoque cobre."),
    kpi("RUPT", "Ruptura", E, PC, "ruptura_pct", tags=[DIR],
        rule="Itens com giro e disponível ≤ 0 (QTESTGER − QTRESERV − QTBLOQUEADA, régua de PKG_REPOSICAOLOJAS).", desc="Falta de produto com demanda."),
    kpi("GIRO", "Giro de estoque", E, PP, "giro_estoque",
        rule="CMV do mês ÷ estoque a custo.", desc="Velocidade com que o estoque se renova."),
    kpi("VPERD", "Venda perdida por falta", E, PC, "venda_perdida_qtd",
        rule="PCEST.QTVENDAPERDIDA (o ERP acumula na venda sem estoque).", desc="Unidades que deixaram de ser vendidas."),
    kpi("CAP_PARADO", "Capital parado", E, PF, "capital_parado",
        rule="PCEST com saldo e QTVENDMES = 0, a custo. Ver também FIMESTOQUE.", desc="Mercadoria que não gira."),
    kpi("CAP_PARADO_PCT", "Capital parado sobre o estoque", E, PF, "capital_parado_pct",
        rule="Capital parado ÷ estoque a custo.", desc="Parcela do estoque sem giro."),
    kpi("SEM_GIRO", "Itens sem giro", E, PP, "itens_sem_giro_pct",
        rule="Itens com saldo e sem venda no mês ÷ itens com saldo.", desc="Amplitude do problema de giro."),
    kpi("EXCESSO", "Excesso sobre o estoque máximo", E, PF, "excesso_estoque",
        rule="(QTESTGER − ESTMAX) × CUSTOREAL quando acima. ESTMAX = DIASESTOQUEMAX × QTGIRODIA quando automático.", desc="Compra além do necessário."),
    kpi("ABAIXO_MIN", "Itens abaixo do mínimo", E, PP, "abaixo_minimo_pct",
        rule="QTESTGER < ESTMIN nos itens com mínimo definido (gatilho de reposição).", desc="Risco de ruptura iminente."),
    kpi("SKUS", "SKUs com estoque", E, PP, "skus_com_estoque",
        rule="Produtos ativos com QTESTGER > 0.", desc="Portfólio disponível para vender."),
    kpi("BLOQ_EST", "Estoque bloqueado", E, PF, "estoque_bloqueado",
        rule="PCEST.QTBLOQUEADA × custo (avaria/quarentena, MOTIVOBLOQESTOQUE).", desc="Mercadoria travada."),
    kpi("VALIDADE", "Estoque a vencer em 30 dias", E, PF, requer=["PCLOTE"],
        rule="PCLOTE.DTVALIDADE nos próximos 30 dias × custo (FEFO do WMS; lote vencido devolve 0 em ESTOQUE_DISPONIVEL_LOTE_VENDA).",
        desc="Valor em risco por vencimento.", unit="R$", polarity="menor_melhor", aggregation="ultimo"),
    kpi("INVENT", "Itens sem inventário há +90 dias", E, PP, requer=["PCEST.DTULTINVENT"],
        rule="PCEST.DTULTINVENT anterior a 90 dias.", desc="Aging de contagem.", unit="%", polarity="menor_melhor", aggregation="ultimo"),
    kpi("DIVERG_RECEB", "Divergências no recebimento", E, PP, requer=["PCNFENTPREENT", "PCMOVPREENT"],
        rule="PCMOVPREENT.QUALDIVERGENCIA na pré-entrada (rotina 1309).", desc="Conferência pedido × nota.", unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ----------------------------------------------------------------- COMPRAS
    kpi("COMPRAS", "Compras (entradas)", K, PF, "compras_valor",
        rule="PCNFENT por DTENT, agrupada por NUMTRANSENT (uma linha por conta contábil). Devoluções de cliente também entram na PCNFENT — filtrar por tipo.",
        desc="Quanto foi comprado de fornecedores."),
    kpi("NF_ENT", "Notas de entrada", K, PP, "qtd_notas_entrada",
        rule="Contagem de PCNFENT no mês.", desc="Volume de recebimentos."),
    kpi("FORN_ATIVOS", "Fornecedores com compra", K, PP, "fornecedores_ativos",
        rule="CODFORNEC distintos com nota no mês.", desc="Amplitude da base de fornecimento."),
    kpi("COMPRA_MEDIA", "Compra média por nota", K, PF, "compra_media_por_nota",
        rule="PCNFENT.VLTOTAL médio.", desc="Tamanho médio do lote comprado."),
    kpi("COMPRAS_PCT", "Compras sobre faturamento", K, PF, "compras_pct_faturamento",
        rule="Entradas ÷ faturamento.", desc="Ritmo de compra contra a venda."),
    kpi("TOP5_FORN", "Concentração nos 5 maiores fornecedores", K, PP, "concentracao_top5_fornecedores_pct",
        rule="Fatia das compras nos 5 maiores CODFORNEC.", desc="Dependência de fornecedores."),
    kpi("FRETE_COMPRA", "Frete sobre compras", K, PF, "frete_compras_pct",
        rule="PCNFENT.VLFRETE ÷ VLTOTAL.", desc="Custo logístico de entrada."),
    kpi("PED_COMPRA_ATRASO", "Pedidos de compra atrasados", K, PP, requer=["PCPEDIDO", "PCITEM"],
        rule="PCPEDIDO.DTPREVENT vencida com saldo a entregar.", desc="Fornecedor atrasando a reposição.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("CUSTO_SUBIU", "Itens com custo de entrada acima da média", K, PF, requer=["PCCONSOLIDAMES"],
        rule="PCEST.CUSTOULTENT vs PCCONSOLIDAMES.VLULTENTMES (11 meses, FUNCOESCOMPRAS).",
        desc="Sentinela de custo de entrada.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("VERBA", "Verba de fornecedor a receber", K, PF, requer=["PCVERBA", "PCESTCRFOR"],
        rule="PCVERBA / PCMOVCRFOR / PCESTCRFOR — o dinheiro do fornecedor.", desc="Verba negociada ainda não recebida.", unit="R$", polarity="maior_melhor", aggregation="ultimo"),

    # --------------------------------------------------------------- LOGÍSTICA
    kpi("CARGAS", "Cargas expedidas", L, PP, "cargas_expedidas",
        rule="PCCARREG com DTSAIDA no período e DT_CANCEL nula (a tabela não tem POSICAO).", desc="Volume de expedição."),
    kpi("NFCARGA", "Notas por carga", L, PP, "notas_por_carga",
        rule="PCCARREG.NUMNOTAS ÷ cargas.", desc="Densidade de entrega."),
    kpi("TON", "Peso entregue", L, PP, "peso_entregue_ton",
        rule="PCCARREG.TOTPESO somado, em toneladas.", desc="Volume físico movimentado."),
    kpi("FRETE", "Frete sobre faturamento", L, PF, "frete_pct_faturamento", tags=[DIR],
        rule="PCCARREG.VLFRETE ÷ faturamento.", desc="Peso do custo de entrega."),
    kpi("VL_CARGA", "Valor médio por carga", L, PF, "valor_medio_por_carga",
        rule="PCCARREG.VLTOTAL médio (totais oficiais vêm de PCNFSAID, excluindo transferências).", desc="Valor por viagem."),
    kpi("KG_CARGA", "Peso médio por carga", L, PP, "peso_medio_por_carga_kg",
        rule="PCCARREG.TOTPESO médio.", desc="Ocupação do veículo."),
    kpi("ROTA_DIAS", "Tempo médio em rota", L, PP, "tempo_medio_rota_dias",
        rule="DTRETORNO − DTSAIDA das cargas que retornaram.", desc="Duração da viagem."),
    kpi("EM_ROTA", "Cargas em rota", L, PP, "cargas_em_rota",
        rule="DTSAIDA preenchida e DTRETORNO nula.", desc="Veículos na rua agora."),
    kpi("CARGA_CANC", "Cargas canceladas", L, PP, "cargas_canceladas_pct",
        rule="PCCARREG.DT_CANCEL preenchida ÷ cargas do período.", desc="Retrabalho na expedição."),
    kpi("FRETE_KG", "Frete por kg", L, PF, "custo_frete_por_kg",
        rule="VLFRETE ÷ TOTPESO das cargas.", desc="Custo unitário de transporte."),
    kpi("FRETE_NOTA", "Frete por nota entregue", L, PF, "custo_frete_por_nota",
        rule="VLFRETE ÷ NUMNOTAS das cargas.", desc="Custo por entrega."),
    kpi("FAT_DIA", "Pedidos faturados no mesmo dia", L, PP, "pedidos_faturados_no_dia_pct",
        rule="PCPEDC.DTFAT = DATA.", desc="Agilidade do ciclo pedido → nota."),
    kpi("CICLO_CARGA", "Ciclo da carga (montagem → saída)", L, PP, requer=["PCCARREG.DATAMON", "PCCARREG.DTFECHA", "PCCARREG.DATACONF"],
        rule="PCCARREG.DATAMON → DTFECHA → DATACONF → DTFAT → DTSAIDA (funil do ciclo, estudo L2).",
        desc="Horas entre montar a carga e o veículo sair.", unit="h", polarity="menor_melhor", aggregation="media", decimals=1),
    kpi("KM", "Km rodados por carga", L, PP, requer=["PCCARREG.KMINICIAL", "PCCARREG.KMFINAL"],
        rule="PCCARREG.KMFINAL − KMINICIAL no acerto.", desc="Produtividade de frota.", unit="km", polarity="menor_melhor", aggregation="media", decimals=1),
    kpi("ATRASO_ENTREGA", "Cargas além do prazo de rota", L, PC, requer=["PCROTAEXP.PRAZOPREVENT"],
        rule="DTSAIDAVEICULO + PCROTAEXP.PRAZOPREVENT < hoje e DTRETORNO nula.", desc="Entregas atrasadas na rua.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("OCORRENCIA", "Ocorrências de entrega", L, PC, requer=["FUSIONTRAK_INT_EVENTOS", "PCMENS"],
        rule="Eventos TIPO = 7 do FusionTrak viram PCMENS; devolução parcial/total por ocorrência.", desc="Problemas na entrega.", unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ------------------------------------------------------------------ FISCAL
    kpi("NFE_AUT", "NF-e autorizadas", X, PP, "nfe_autorizadas_pct",
        rule="PCNFSAID.SITUACAONFE = 100 sobre as notas com situação preenchida.", desc="Saúde da emissão fiscal."),
    kpi("NF_CANC", "Notas canceladas", X, PP, "notas_canceladas_pct",
        rule="PCNFSAID.DTCANCEL preenchida (P_PC_CACELA_NF); detalhe em PCNFCAN.", desc="Retrabalho fiscal."),
    kpi("ICMS", "ICMS sobre faturamento", X, PF, "icms_pct_faturamento",
        rule="PCNFSAID.VLICMS ÷ VLTOTAL (PKG_TRIBUTACAO).", desc="Peso do ICMS."),
    kpi("ST", "ICMS-ST sobre faturamento", X, PF, "st_pct_faturamento",
        rule="PCNFSAID.VLST ÷ VLTOTAL.", desc="Peso da substituição tributária."),
    kpi("IPI", "IPI sobre faturamento", X, PF, "ipi_pct_faturamento",
        rule="PCNFSAID.VLIPI ÷ VLTOTAL.", desc="Peso do IPI."),
    kpi("TRIB", "Carga tributária na saída", X, PF, "carga_tributaria_pct",
        rule="ICMS + ST + IPI ÷ faturamento.", desc="Tributos embutidos na venda."),
    kpi("NF_DIA", "Notas por dia útil", X, PP, "notas_por_dia_util",
        rule="Notas faturadas ÷ dias úteis (seg–sex) do período.", desc="Ritmo diário de emissão."),
    kpi("DENEGADA", "NF-e denegadas ou rejeitadas", X, PP, requer=["PCNFSAID.SITUACAONFE (110/205/301/302)"],
        rule="SITUACAONFE em 110/205/301/302; contingência em PKG_CONTINGENCIA_SVC.", desc="Notas que a SEFAZ recusou.", unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),
    kpi("MDFE", "MDF-e pendentes de transmissão", X, PP, requer=["PCMANIFESTOELETRONICOC"],
        rule="PCMANIFESTOELETRONICOC.SITUACAOMDFE = 0 com UTILIZAMDFE = S na filial.", desc="Cargas sem manifesto.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("NUMERACAO", "Falhas de numeração de NF", X, PP, requer=["PCLOGALTERACAODADOS"],
        rule="PCLOGALTERACAODADOS com 'ERRO NA BUSCA NO PROXIMO NUMERO DE NOTA' (OBTERPROXIMONUMERONOTANFE).", desc="Erros de emissão em série.", unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ------------------------------------------------------------------ PESSOAS
    kpi("HC", "Headcount", R, PA, "headcount", tags=[DIR],
        rule="PCEMPR com ADMISSAO ≤ data e sem DTDEMISSAO (SITUACAO A).", desc="Tamanho da equipe."),
    kpi("TURN", "Turnover", R, PA, "turnover_pct", tags=[DIR],
        rule="(admissões + demissões) ÷ 2 sobre o headcount.", desc="Rotatividade."),
    kpi("DESLIG", "Desligamentos", R, PA, "desligamentos",
        rule="PCEMPR.DTDEMISSAO no mês.", desc="Saídas."),
    kpi("ADM", "Admissões", R, PA, "admissoes",
        rule="PCEMPR.ADMISSAO no mês.", desc="Entradas."),
    kpi("CASA", "Tempo médio de casa", R, PA, "tempo_medio_casa_anos",
        rule="Média de anos desde ADMISSAO dos ativos.", desc="Retenção."),
    kpi("MOTORISTAS", "Motoristas ativos", R, PP, "motoristas_ativos",
        rule="PCEMPR.TIPOMOTORISTA preenchido e ativo (mesmo dado que alimenta o MyFrota).", desc="Capacidade de entrega própria."),
    kpi("FAT_FUNC", "Faturamento por funcionário", R, PF, "faturamento_por_funcionario",
        rule="Faturamento ÷ headcount.", desc="Produtividade da empresa."),
    kpi("CNH", "CNH de motorista vencendo em 30 dias", R, PP, requer=["PCEMPR.DTVALIDADECNH"],
        rule="PCEMPR.DTVALIDADECNH nos próximos 30 dias.", desc="Risco operacional e legal.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("USUARIO_DESLIG", "Usuários ativos de funcionários desligados", R, PP, requer=["PCEMPR.DTDEMISSAO x PCEMPR.USUARIOBD"],
        rule="PCEMPR com DTDEMISSAO e usuário ainda habilitado (ver PCLOGUSUARIO).", desc="Brecha de segurança.", unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
]
