"""Catálogo de KPIs do WinThor — o que a empresa pluga com um clique.

Fonte: estudos do extrator (Recife Doces, Nordeste Boi, MakFrios) sobre o
schema e o PL/SQL do WinThor mais o SQL capturado em runtime. Cada item tem
duas camadas:

- para o CLIENTE: `desc` (o que mede), `calc` (como é calculado, sem termo
  técnico) e `why` (por que importa e o que fazer com o número);
- para o ROOT: `rule`, a regra real do ERP (tabela, coluna, rotina/package).

Quando a métrica já existe no espelho (`erp_metric`), o KPI nasce calculado;
quando depende de tabela ainda fora do plano de coleta, vai como `planejado`
com a lista `requer` — aparece no catálogo, mas não pluga até a coleta existir.

Semeado em `KpiTemplate` por `manage.py seed_kpi_winthor` (idempotente).
"""

V, C, F, E, K, L, X, R = "vendas", "clientes", "financeiro", "estoque", "compras", "logistica", "fiscal", "rh"
PF, PC, PP, PA = "financeira", "clientes", "processos", "aprendizado"
DIR = "diretoria"  # tag: entra no resumo executivo


FV, WMS, ROTA = "forca_vendas", "wms", "roteirizacao"           # setores dos sistemas satélites
O_WINTHOR, O_FV, O_WMS, O_ROTA, O_BI, O_TECHSYS = "winthor", "forca_vendas", "wms", "roteirizador", "bi", "techsys"

# Como cada sistema satélite lê o WinThor — o que aprendemos no extrator e
# reproduzimos direto do ERP (mostrado só ao root, no Catálogo técnico).
FONTES = [
    {"key": "winthor", "nome": "WinThor (TOTVS)", "papel": "O ERP. Regras em PL/SQL (PARAMFILIAL, FATURAMENTO, PKG_ESTOQUE, PKG_LIMITECREDITO, F_QTDIASVENCIDOS, ATUALIZACAO_DIARIA) e rotinas PCSISnnnn.",
     "como_le": "É a fonte. O agente TechSys lê as tabelas PC* com usuário somente leitura, por marca d'água (DTULTALTER/DTALTERC5) e janela de meses; reproduz as regras oficiais em vez de aproximar.",
     "tabelas": "PCNFSAID, PCMOV, PCPEDC/PCPEDI, PCPREST, PCLANC, PCEST, PCCARREG, PCNFENT, PCEMPR, PCMETA/PCMETARCA, PCFINANC",
     "aprendemos": "Faturamento (CONDVENDA fora de 4/8/10/13/20/98/99), bonificação 5/6/11/12, dias financeiros no atraso, disponível de estoque, giro QTGIRODIA, meta diária PCMETARCA, fotografia PCFINANC.",
     "exige": ""},
    {"key": "ion", "nome": "Ion Sistemas — força de vendas", "papel": "App do vendedor. Schema IONV_SYNC (92 tabelas): fila IONVS_*, dados prontos IONVD_* (VENDEDOR_PERFORMANCE, METAS, ABC_CLIENTES/PRODUTOS, CLIENTES_HISTVENDAS, POSITIVACAO_*, CLIENTES_CREDDISP, HISTPED_FALTAS/CORTES, DEVOLUCOES).",
     "como_le": "Triggers UPDATE OF em PCPEDC/PCCLIENT enfileiram com deduplicação (NOT EXISTS STATUS='PD'); o serviço dorme em DBMS_ALERT e roda jobs PL/SQL que fazem MERGE nas IONVD_* a partir de PCPEDC, PCNFSAID, PCMOV, PCPREST, PCCLIENT, PCUSUARI.",
     "tabelas": "PCPEDC (VLATEND, POSICAO, CONDVENDA), PCNFSAID (VLTOTGER, CODFISCAL), PCMOV, PCPREST (DTPAG, PCCOB.PAGCOMISSAO), PCCLIENT (LIMCRED), PCFALTA, PCNFENT (devoluções)",
     "aprendemos": "Venda transmitida × faturada, venda bloqueada (POSICAO B), lucratividade = (venda − CUSTOFIN) ÷ venda, comissão por título pago (CFOP 511/611/512/612/711/712) com estorno via PCESTCOM, curva ABC por RANK/RATIO_TO_REPORT, crédito = limite + crédito + sazonal − títulos − pedidos − cheques, positivação por pedido ou por nota (parâmetro).",
     "exige": ""},
    {"key": "maxsolucoes", "nome": "MaxSoluções (maxPedido) — força de vendas", "papel": "Outro app de vendas. Schema MAXSOLUCOES com PCMXS* (PRODUTPOS, MIXCLIENTES, CLIENTECREDDISP, QTDEPRODVENDA, EST, HISTCANCELPED).",
     "como_le": "Processador.dll roda blocos PL/SQL com a consulta em texto (VQUERY), grava numa _TEMP e faz MERGE com máscara (apaga o que sumiu). Lê PCPEDC/PCPEDI para positivação do dia e PCNFSAID/PCMOV para o histórico.",
     "tabelas": "PCPEDC/PCPEDI, PCNFSAID/PCMOV, PCCLIENT, PCPREST, PCEST, PCUSUARI",
     "aprendemos": "Positivação de produto por RCA/cliente (pedido do dia ∪ nota), mix por cliente com preço tabela × praticado, crédito disponível com a mesma fórmula da Ion, quantidade vendida por cliente × produto × dia.",
     "exige": ""},
    {"key": "geo", "nome": "BI / geomarketing (schema GEO)", "papel": "Funções pipelined F_BI_* (carteira, clientes, clientes sem venda no mês, corte, devolução, financeiro, metas por depto/seção/fornecedor, venda perdida, visitas, roteiro) e views VIEW_BI_* replicadas por materialized view.",
     "como_le": "Lê o ERP por sinônimo e MLOG$ (materialized view logs); cada função é uma consulta SIG (100 carteira, 400 devolução, 500 financeiro, 800 corte) sobre PCPEDC, PCNFSAID, PCPREST, PCCORTEI, PCESTCOM, PCMETA/PCMETARCA, PCROTACLI.",
     "tabelas": "PCPEDC, PCNFSAID, PCPREST, PCCLIENT, PCUSUARI, PCCORTEI, PCESTCOM/PCNFENT, PCMETA, PCMETARCA, PCDATAS, PCROTACLI",
     "aprendemos": "Carteira = clientes do RCA sem exclusão; inativo = DTULTCOMP mais antiga que NUMDIASCLIINATIV (PCCONSUM, 90); clientes perdidos = positivados no mês anterior sem compra no atual; corte em valor = QTCORTADA × PVENDA (PCCORTEI); devolução em peso e valor via PCESTCOM.DTESTORNO; meta × venda por dia (PCDATAS × PCMETARCA); meta por departamento (PCMETA tipo D).",
     "exige": ""},
    {"key": "fusiontrak", "nome": "FusionTrak — roteirização e telemetria", "papel": "Schema FUSIONT: FUSIONTRAK_INT_ERP (fila de deltas), INT_CARGA (carga enviada ao roteirizador), INT_CARGA_ENT (ordem de entrega), CARGAS_ROTEIRIZADAS, INT_EVENTOS (o que aconteceu na rua).",
     "como_le": "Triggers TR_FUSIONT_* em PCPEDC e PCMOVENDPEND gravam deltas por campo (CAMPO_ALT, VALOR_OLD/NEW, SN_INT_REG); FUSION_INTEGRADOR.exe consome, monta a carga e devolve eventos (km, GPS, motivo de devolução/reentrega).",
     "tabelas": "PCPEDC (ORIGEMPED fora de B/R/A, CONDVENDA 1/5/8/10), PCCARREG, PCMOVENDPEND, PCROTAEXP",
     "aprendemos": "Ocupação do veículo (peso ÷ capacidade), entregas e cidades por carga, ordem de entrega, ocorrências; e que o WinThor já guarda NUMENT/NUMCID/KM por carga — o que dá os mesmos KPIs sem o roteirizador.",
     "exige": "FusionTrak instalado (schema FUSIONT com GRANT)"},
    {"key": "wms", "nome": "WMS do WinThor", "papel": "Módulo do próprio ERP: PCMOVENDPEND (OS), PCESTENDERECO, PCWMS, PCVOLUMEOS, WMS_PROCESSACORTE, RF 3723/3734.",
     "como_le": "Não é satélite: são rotinas do WinThor. O agente agrega PCMOVENDPEND por NUMOS (linhas, QT, QTSEPARADA, QTCONFERIDA, QTCANCEL, QTERROS, início/fim de separação e conferência).",
     "tabelas": "PCMOVENDPEND, PCESTENDERECO, PCCORTE/PCCORTEI, PCWMSCORTE",
     "aprendemos": "DTFIMSEPARACAO só é carimbada quando QTSEPARADA = QT; o faturamento da carga trava com OS aberta (WMS_EXISTPENDENCIASEPWMS); corte devolve reserva e flex.",
     "exige": "Módulo WMS do WinThor em uso (PCFILIAL.USAWMS = S)"},
    {"key": "bsnotas", "nome": "BS-Notas (Brunsker) — replicador de notas", "papel": "CDC por gatilho: triggers TRG_BSNT_* gravam o ROWID alterado em filas BSNT_*; PKG_BS_CLIENT_* faz polling em lotes de 1.000 e devolve o pacote por cliente/banco.",
     "como_le": "Junta a fila com a tabela real pelo ROWID (SINC_ROWID) e apaga a marca depois de entregar. Lê 30 tabelas, sobretudo PCNFENT/PCNFENTXML (pré-entrada de NF-e), PCTRIBENTPROD, PCCONTA, PCTABPR, PCNEGFORNEC.",
     "tabelas": "PCNFENT, PCNFENTXML, PCNFSAID, PCESTCOM, PCTRIBENTPROD, PCNEGFORNEC",
     "aprendemos": "Padrão de replicação barato (marca por ROWID); devolução ligada à venda por PCESTCOM.NUMTRANSVENDA; PCNFENT.TIPODESCARGA distingue compra de devolução.",
     "exige": "Só quem usa o BS-Notas; nada a reproduzir em KPI"},
    {"key": "abt", "nome": "ABT / MyBanks / PixPay — financeiro bancário", "papel": "Schema ABT com ABINTEGRACAOCONTROLEMYBANKS (controle de reintegração) e ABCONTROLEPIXPAY (QR code, TXID, baixa via PIX).",
     "como_le": "Triggers TRG_*_MYBANKS_UPDATE em PCPREST, PCLANC, PCBANCO, PCCLIENT, PCNFSAID marcam DEVE_ATUALIZAR = S; a stack Node (main.js/server.js, que se identifica com SET_MODULE/SET_IDENTIFIER) lê e processa.",
     "tabelas": "PCPREST (nosso número, código de barras, PIX), PCLANC, PCBANCO, PCMOVCR",
     "aprendemos": "Estado do título para cobrança bancária e PIX (BAIXADOVIAPIX, VLRDIFBAIXA); o job ABGERACAODADOSBANCARIOS do ERP estava desabilitado — a régua de cobrança é externa.",
     "exige": "Só quem usa MyBanks/PixPay; KPIs de cobrança saem da PCPREST de qualquer WinThor"},
    {"key": "deps", "nome": "DEPS — crédito e liberação de pedido", "papel": "Schema DEPS com package INTEGRACAO (procedures CLIENTE e PEDIDO) consumido por um SQL Server via linked server.",
     "como_le": "Porta oficial por package com contrato: altera limite e posição do pedido chamando procedures que gravam TB_LOG_CLIENTE/TB_LOG_PEDIDO; lê PCCLIENT, PCPREST, PCPEDC, PCBLOQUEIOSPEDIDO, PCFALTA, PCCARREG por sinônimo.",
     "tabelas": "PCCLIENT, PCPREST, PCPEDC, PCBLOQUEIOSPEDIDO, PCFALTA, PCCOB",
     "aprendemos": "O desenho certo para escrever no ERP (exceções nomeadas, mapa de usuário, log com antes/depois). Para KPI: fila de bloqueio e liberação de crédito.",
     "exige": "Só quem tem a análise de crédito externa"},
    {"key": "maxpromotor", "nome": "MaxPromotor — trade marketing", "papel": "Views PROIV_* no schema MAXPROMOTOR (PONTOVENDA, PEDIDO, MIX, ROTA, ITEM_AVALIADO, USUARIO), lidas por JDBC.",
     "como_le": "Views que já entregam o layout do parceiro em UTF-8 (CONVERT_UTF8) por data de alteração: PROIV_PEDIDO = PCPEDC × PCPEDI × PCNFSAID com valor unitário zerado em bonificação; PROIV_MIX = itens de pedidos do força de vendas (CODEMITENTE 8888); PROIV_ROTA = PCROTACLI com periodicidade.",
     "tabelas": "PCPEDC/PCPEDI, PCNFSAID, PCCLIENT, PCROTACLI, PCPRODUT/hierarquia",
     "aprendemos": "Mix por cliente a partir do pedido; roteiro de visita (PCROTACLI: periodicidade, próxima visita) — base do KPI de visitas planejadas × realizadas.",
     "exige": ""},
    {"key": "sellout", "nome": "Henkel / M. Dias Branco — sell-out para indústria", "papel": "Schemas HENKEL (views HENKEL_CLIENT, HENKEL_INVOICE_INVOICEITEM, HENKEL_PRODUCTSTOCK, HENKEL_PRODUCTBATCH) e MDIASBRANCO (sinônimos).",
     "como_le": "ImplantaIt.GenericExtractor lê as views por distribuidor e data (codi_rev, data_ven), filtrando o fornecedor da indústria (codfornec 1804); M. Dias Branco lê direto por sinônimo via JDBC.",
     "tabelas": "PCNFSAID/PCMOV (venda por produto e cliente), PCEST (estoque), PCLOTE (lote/validade), PCCLIENT, PCPRODUT",
     "aprendemos": "O layout de sell-out por fornecedor: venda, estoque e lote por produto — base para KPI de venda e estoque por fornecedor/indústria.",
     "exige": ""},
    {"key": "pdv", "nome": "MonitorPDV / Scanntech / Frotix / PagueBem", "papel": "PDV de loja (schema MONITORPDV, 220 tabelas TB_*: preços, produtos, cargas para os caixas), Scanntech (sell-out de varejo via AcruxMonitorService), Frotix (FRX_TB_PEDIDOS/LOTES — expedição e reentrega), PagueBem (crédito).",
     "como_le": "O PDV recebe cargas de preço/produto (TB_PRODPRECO por NROCARGA) e devolve cupons; Frotix enfileira pedidos por trigger FRX_TRG_PCPEDC_INSERT e sincroniza lotes via Node.",
     "tabelas": "PCPRODUT/PCTABPR/PCEMBALAGEM (preço por código de barras), PCPEDC (reentrega), PCNFSAID (cupom)",
     "aprendemos": "Varejo: preço por filial/embalagem e sincronismo de carga para o caixa; reentrega como evento de pedido.",
     "exige": "Só quem tem loja/PDV; a venda de loja já está em PCNFSAID"},
]


def kpi(code, name, sector, perspective, metric="", target="", *, rule="", desc="", calc="", why="", tags=(),
        filters=None, requer=(), unit=None, polarity=None, aggregation=None, decimals=None,
        origem=O_WINTHOR, sistema=""):
    """`unit/polarity/aggregation/decimals` vêm da métrica quando existe; aqui só sobrescrevem.

    `origem`: de onde veio a inteligência (regra do WinThor, aprendida da força de
    vendas, do WMS, do roteirizador, ou composição nossa). `sistema`: o que o
    cliente precisa ter além do WinThor ("" = qualquer banco WinThor serve).
    """
    return {
        "code": code, "name": name, "sector": sector, "perspective": perspective,
        "erp_metric": metric, "erp_target": target, "rule": rule, "description": desc,
        "explanation": calc, "importance": why, "origin": origem, "requires_system": sistema,
        "tags": list(tags), "default_filters": filters or {}, "requer": list(requer),
        "unit": unit, "polarity": polarity, "aggregation": aggregation, "decimals": decimals,
    }


CATALOGO = [
    # ------------------------------------------------------------------ VENDAS
    kpi("FAT", "Faturamento líquido", V, PF, "faturamento", "vlvendaprev", tags=[DIR],
        rule="PCNFSAID: soma de VLTOTAL das notas de saída não canceladas (DTCANCEL nula), fora CONDVENDA 4/8/10/13/20/98/99 e bonificação 5/6/11/12 — a mesma régua da view SQL_INTEGRACAO_NF_VENDAS. Meta: PCMETARCA (meta diária por RCA) ou PCUSUARI.VLVENDAPREV.",
        desc="O que a empresa faturou de fato.",
        calc="Soma o valor das notas fiscais de venda emitidas no período. Notas canceladas, bonificações, transferências entre filiais e entregas futuras ficam de fora — a mesma regra que o WinThor usa nos relatórios de faturamento.",
        why="É o número de referência de todos os outros. Compare com a meta e com o mesmo mês do ano anterior; queda com positivação estável indica ticket menor, queda com positivação caindo indica perda de clientes."),
    kpi("FAT_YOY", "Crescimento do faturamento (ano a ano)", V, PF, "crescimento_faturamento_yoy_pct", tags=[DIR],
        rule="Faturamento do período ÷ faturamento do mesmo período do ano anterior (PCNFSAID.DTSAIDA).",
        desc="Se a empresa está crescendo ou encolhendo.",
        calc="Compara o faturamento do período com o do mesmo período do ano passado e mostra a variação em %.",
        why="Elimina a sazonalidade: dezembro contra dezembro, não contra novembro. Abaixo da inflação significa encolhimento real."),
    kpi("NOTAS", "Notas emitidas", V, PP, "qtd_notas",
        rule="Contagem de PCNFSAID faturadas (mesma régua do faturamento).",
        desc="Volume de vendas em documentos.",
        calc="Conta as notas fiscais de venda do período, com a mesma regra do faturamento.",
        why="Mostra o volume de operação independente do valor. Notas subindo e faturamento parado indica ticket caindo."),
    kpi("TKT", "Ticket médio", V, PC, "ticket_medio", "vlmediopedido",
        rule="Faturamento ÷ notas. Meta em PCMETA.VLMEDIOPEDIDO quando a rotina 3305 é usada.",
        desc="Quanto cada venda carrega em média.",
        calc="Faturamento dividido pelo número de notas.",
        why="Crescer o ticket é o jeito mais barato de crescer: mais itens por pedido ou mix mais valioso, sem custo de entrega adicional."),
    kpi("POSIT", "Clientes positivados", V, PC, "positivacao", "clipos", tags=[DIR],
        rule="Clientes distintos com nota faturada no mês — a apuração da rotina 111 (QTPOSITIVACAOFATURADOS). Meta: PCMETARCA.NUMCLIPOS ou PCMETA.CLIPOSPREV.",
        desc="Quantos clientes compraram no mês.",
        calc="Conta os clientes diferentes que tiveram pelo menos uma nota de venda no período.",
        why="É a base do faturamento: cliente que não positiva este mês é candidato a inativo no próximo. Acompanhe por vendedor e por rota."),
    kpi("POS_RCA", "Clientes positivados por RCA", V, PC, "clientes_por_rca",
        rule="Positivação ÷ RCAs com venda (PCNFSAID.CODUSUR).",
        desc="Cobertura média da carteira por vendedor.",
        calc="Clientes positivados divididos pelos vendedores que venderam no período.",
        why="Mede a cobertura de rota. Vendedor abaixo da média está concentrando em poucos clientes ou deixando a carteira sem visita."),
    kpi("RCAS", "RCAs com venda", V, PP, "rcas_ativos",
        rule="CODUSUR distintos com nota faturada no mês.",
        desc="Quantos vendedores produziram.",
        calc="Conta os vendedores que tiveram ao menos uma nota faturada no período.",
        why="Vendedor cadastrado sem venda é custo fixo sem retorno. Compare com o total da equipe."),
    kpi("VENDA_RCA", "Venda média por RCA", V, PF, "venda_media_por_rca",
        rule="Faturamento ÷ RCAs com venda.",
        desc="Produtividade média da equipe de vendas.",
        calc="Faturamento dividido pelos vendedores que venderam.",
        why="Referência para meta individual e para decidir se a equipe cresce ou se a carteira é redistribuída."),
    kpi("PEDIDOS", "Pedidos digitados", V, PP, "qtd_pedidos", "pedidosprev",
        rule="PCPEDC por DATA, excluindo POSICAO C. Meta: PCMETARCA.QTPEDPREV.",
        desc="Entrada de pedidos, antes de faturar.",
        calc="Conta os pedidos digitados no período que não foram cancelados.",
        why="É o termômetro mais rápido da demanda: cai antes do faturamento cair. Compare com a meta de pedidos do vendedor."),
    kpi("PED_MEDIO", "Pedido médio", V, PC, "pedido_medio",
        rule="PCPEDC.VLTOTAL médio dos pedidos não cancelados.",
        desc="Tamanho médio do pedido digitado.",
        calc="Valor total dos pedidos dividido pela quantidade de pedidos.",
        why="Pedido médio caindo com mais pedidos indica pulverização: mais entregas pequenas, mais custo logístico por real vendido."),
    kpi("PED_CANC", "Pedidos cancelados", V, PP, "pedidos_cancelados_pct",
        rule="PCPEDC.POSICAO = C sobre os pedidos do período.",
        desc="Quanto do que foi digitado morreu antes de faturar.",
        calc="Pedidos cancelados divididos pelo total de pedidos do período.",
        why="Cancelamento alto aponta problema de crédito, de estoque ou de digitação. Olhe o motivo antes de cobrar o vendedor."),
    kpi("CONV", "Conversão pedido → nota", V, PP, "conversao_pedido_nota_pct",
        rule="Pedidos com POSICAO F (DTFAT preenchida) sobre os digitados no mês.",
        desc="Eficiência do funil pedido → faturamento.",
        calc="Pedidos que viraram nota fiscal divididos pelos pedidos digitados no período.",
        why="O que não converte fica preso em bloqueio, falta de estoque ou carga. Conversão baixa é venda perdida depois de conquistada."),
    kpi("CARTEIRA", "Carteira de pedidos", V, PF, "carteira_pedidos",
        rule="PCPEDC pendentes (POSICAO L/M/B/P) — o que ainda vai faturar.",
        desc="Venda já vendida e ainda não faturada.",
        calc="Soma o valor dos pedidos que ainda não foram faturados nem cancelados.",
        why="É o faturamento dos próximos dias. Carteira crescendo sem faturar indica gargalo na separação ou na liberação."),
    kpi("MIX", "Mix de produtos vendidos", V, PC, "mix_skus",
        rule="CODPROD distintos em PCMOV de venda no mês. Meta possível em PCMETA.MIXPREV.",
        desc="Amplitude do portfólio que gira.",
        calc="Conta os produtos diferentes que tiveram venda no período.",
        why="Mix estreito concentra risco em poucos itens e deixa o restante do estoque parado. Meta de mix por vendedor amplia a cesta do cliente."),
    kpi("ITENS_NOTA", "Itens por nota", V, PC, "itens_por_nota",
        rule="Linhas de PCMOV (operações de venda) ÷ notas faturadas.",
        desc="Profundidade média da compra do cliente.",
        calc="Total de itens vendidos dividido pelo número de notas.",
        why="Cada item a mais por nota é faturamento sem custo de entrega extra. É o KPI de venda sugestiva."),
    kpi("FREQ", "Frequência de compra", V, PC, "notas_por_cliente",
        rule="Notas ÷ clientes positivados.",
        desc="Quantas vezes o cliente compra no mês.",
        calc="Notas do período divididas pelos clientes positivados.",
        why="Frequência caindo antecipa churn: o cliente compra menos vezes antes de parar de comprar."),
    kpi("DESC", "Desconto médio praticado", V, PF, "desconto_medio_pct",
        rule="PCMOV: 1 − PUNIT/PTABELA ponderado por quantidade. Limite oficial = menor entre PERMAXDESCVENDA (filial) e PCTABPR.PERDESCMAX.",
        desc="Quanto de preço a equipe cede em média.",
        calc="Compara o preço praticado com o preço de tabela nos itens vendidos e mostra a diferença em %, ponderada pela quantidade.",
        why="Um ponto de desconto a menos vai direto para a margem. Acompanhe por vendedor: desconto no teto costuma ser hábito, não necessidade."),
    kpi("BONIF", "Bonificação sobre faturamento", V, PF, "bonificacao_pct",
        rule="Notas CONDVENDA 5/6/11/12 (VLBONIFIC) sobre o faturamento.",
        desc="Custo comercial de brindes e bonificações.",
        calc="Valor das notas de bonificação e brinde dividido pelo faturamento.",
        why="Bonificação é desconto disfarçado. Sem teto, corrói a margem; compare com a verba negociada com o fornecedor."),
    kpi("DEVOL", "Devoluções sobre vendas", V, PC, "devolucoes_pct",
        rule="PCMOV operações E1/ED/EL sobre as de venda. No ERP a devolução é PCNFENT.TIPODESCARGA 6/7 ligada à venda por PCESTCOM.NUMTRANSVENDA.",
        desc="Quanto do que foi vendido voltou.",
        calc="Valor devolvido pelos clientes dividido pelo valor vendido no período.",
        why="Devolução custa duas vezes: o frete de ida e o de volta, além do produto que pode voltar avariado. Olhe por rota, motorista e produto."),
    kpi("CORTE", "Pedidos com corte", V, PP, "corte_pct",
        rule="PCPEDC com PCPEDI.QTFALTA > 0 (falta de estoque na separação). A autoria do corte fica em PCCORTEFV.",
        desc="Pedidos entregues a menos por falta.",
        calc="Pedidos em que algum item foi entregue em quantidade menor que a pedida, divididos pelo total de pedidos.",
        why="Corte é venda perdida com o cliente já conquistado e custo de entrega já pago. É o elo entre vendas e compras."),
    kpi("QT_CORTE", "Quantidade cortada nos pedidos", V, PP, "venda_perdida_corte",
        rule="Soma de PCPEDI.QTFALTA nos pedidos do período; a falta na importação vira PCFALTA.",
        desc="Volume de venda perdida por ruptura.",
        calc="Soma as unidades que foram pedidas e não puderam ser entregues por falta de estoque.",
        why="Transforma a ruptura em número: priorize a compra dos itens que mais cortam."),
    kpi("TOP10_CLI", "Concentração nos 10 maiores clientes", V, PC, "concentracao_top10_clientes_pct",
        rule="Fatia do faturamento dos 10 maiores CODCLI do período.",
        desc="Risco de dependência de poucos clientes.",
        calc="Soma o faturamento dos 10 maiores clientes do período e divide pelo faturamento total.",
        why="Acima de 40% a perda de um cliente grande derruba o mês. Diversificar a base protege o caixa."),
    kpi("TOP_RCA", "Dependência do maior RCA", V, PP, "concentracao_top_rca_pct",
        rule="Fatia do faturamento do CODUSUR que mais vende.",
        desc="Risco de concentração na equipe.",
        calc="Faturamento do vendedor que mais vende dividido pelo faturamento total.",
        why="Se um vendedor sozinho responde por um quarto da venda, a saída dele vira crise. Vale espelhar a carteira."),
    kpi("PRECO_MEDIO", "Preço médio por unidade", V, PF, "preco_medio_item",
        rule="PCMOV: valor vendido ÷ quantidade.",
        desc="Sinal de mix e de política de preço.",
        calc="Valor vendido dividido pela quantidade de unidades vendidas.",
        why="Preço médio caindo com volume estável indica mix mais barato ou desconto maior — os dois pesam na margem."),
    kpi("PESO_VENDIDO", "Peso vendido", V, PP, "peso_vendido_ton", tags=[DIR],
        rule="SUM(PCMOV.QTCONT × NVL(PCMOV.PESOLIQ, PCPRODUT.PESOLIQ)) — a expressão mais repetida do PL/SQL do WinThor (300+ objetos: faturamento, carregamento, comissão por peso). No espelho: quantidade × PCPRODUT.PESOLIQ.",
        desc="Toneladas vendidas no período.",
        calc="Multiplica a quantidade vendida de cada item pelo peso líquido do produto e soma, em toneladas.",
        why="Em distribuição de alimentos e bebidas o negócio se mede em toneladas: frete, frota e armazém são dimensionados por peso, não por real."),
    kpi("PRECO_KG", "Preço médio por kg", V, PF, "preco_medio_kg",
        rule="Valor vendido ÷ quilos vendidos (PCMOV.QTCONT × PESOLIQ).",
        desc="Quanto se vende por quilo.",
        calc="Valor vendido dividido pelos quilos vendidos.",
        why="Neutraliza a mudança de mix: preço por kg caindo com peso estável é desconto ou mix mais barato."),
    kpi("CUSTO_KG", "Custo médio por kg", F, PF, "custo_medio_kg",
        rule="Custo financeiro dos itens ÷ quilos vendidos.",
        desc="Quanto custa cada quilo vendido.",
        calc="Custo dos itens vendidos dividido pelos quilos vendidos.",
        why="Junto com o preço por kg dá a margem por quilo, a régua de precificação de commodities."),
    kpi("FILA_BLOQ", "Pedidos bloqueados aguardando liberação", V, PP, requer=["PCBLOQUEIOSPEDIDO", "PCMOTBLOQUEIO"],
        rule="PCBLOQUEIOSPEDIDO STATUS = B por motivo (PKG_MOTIVOBLOQUEIO, 26 regras); a liberação pela Integradora apaga a linha, só a rotina 336 marca L.",
        desc="Valor parado em bloqueio comercial ou financeiro.",
        calc="Soma o valor dos pedidos que estão bloqueados esperando alguém liberar.",
        why="Cada hora em bloqueio atrasa a entrega e pode perder a venda. Mostra onde a alçada está lenta.",
        unit="R$", polarity="menor_melhor", aggregation="ultimo"),
    kpi("TEMPO_FILA", "Tempo médio em fila de bloqueio", V, PP, requer=["PCLOGBLOQUEIOPEDVENDA"],
        rule="PCLOGBLOQUEIOPEDVENDA (TRG_PCPEDC) dá a linha do tempo de cada bloqueio.",
        desc="Quanto o pedido espera até ser liberado.",
        calc="Mede o tempo entre o bloqueio do pedido e a liberação, em média.",
        why="Reduzir a fila é ganhar prazo de entrega sem mexer na logística.",
        unit="h", polarity="menor_melhor", aggregation="media", decimals=1),
    kpi("CORTE_WMS", "Corte na separação (WMS)", V, PP, requer=["PCWMSCORTE", "PCCORTEI"],
        rule="WMS_PROCESSACORTE grava PCWMSCORTE/PCCORTEI com produto, motivo e funcionário.",
        desc="Valor cortado na separação, por motivo.",
        calc="Soma o valor dos itens que o armazém cortou na hora de separar, com o motivo registrado.",
        why="Separa a falta real da falha de armazenagem: corte com estoque no sistema é problema de endereço, não de compra.",
        unit="R$", polarity="menor_melhor", aggregation="soma"),
    kpi("FLEX_RCA", "RCAs com flex negativo", V, PF, requer=["PCUSUARI.VLCORRENTE", "PCUSUARI.VLLIMCRED"],
        rule="PC_PKG_CONTROLARSALDORCA: saldo flex em PCUSUARI.VLCORRENTE contra VLLIMCRED.",
        desc="Vendedores que estouraram a conta-corrente de desconto.",
        calc="Conta os vendedores cujo saldo de desconto (flex) está negativo.",
        why="Flex negativo vira desconto sem cobertura. É o alerta antes de a margem da equipe virar prejuízo.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),

    # ---------------------------------------------------------------- CLIENTES
    kpi("BASE", "Base de clientes", C, PC, "base_clientes",
        rule="PCCLIENT não bloqueados e não excluídos.",
        desc="Tamanho da carteira cadastrada.",
        calc="Conta os clientes cadastrados que não estão bloqueados.",
        why="É o potencial de mercado já conquistado. Cresce com prospecção e encolhe com bloqueio e inatividade."),
    kpi("ATIVOS", "Clientes ativos (90 dias)", C, PC, "clientes_ativos", tags=[DIR],
        rule="PCCLIENT.DTULTCOMP nos últimos 90 dias.",
        desc="Carteira que de fato compra.",
        calc="Conta os clientes que compraram nos últimos 90 dias.",
        why="Base ativa é o que sustenta a positivação. Quando cai, o faturamento cai em seguida."),
    kpi("NCLI", "Novos clientes", C, PC, "novos_clientes",
        rule="PCCLIENT.DTPRIMCOMPRA no período (primeira compra).",
        desc="Conquista de clientes.",
        calc="Conta os clientes cuja primeira compra aconteceu no período.",
        why="Repõe a perda natural da base. Meta de novos clientes por vendedor mantém a carteira viva."),
    kpi("CADASTROS", "Clientes cadastrados no mês", C, PC, "clientes_cadastrados",
        rule="PCCLIENT.DTCADASTRO no período.",
        desc="Prospecção que virou cadastro.",
        calc="Conta os cadastros de cliente criados no período.",
        why="Cadastro sem compra é prospecção parada: compare com os novos clientes para ver a conversão."),
    kpi("CHURN", "Churn de clientes", C, PC, "churn_clientes_pct", tags=[DIR],
        rule="Clientes que compraram no trimestre anterior e não compraram no corrente (PCNFSAID).",
        desc="Perda de clientes ativos.",
        calc="Dos clientes que compraram no trimestre anterior, mostra a % que não comprou no trimestre atual.",
        why="Recuperar um cliente custa menos que conquistar um novo. Churn acima de 10% ao trimestre pede ação de reativação."),
    kpi("INATIVOS", "Clientes inativos (+90 dias)", C, PC, "clientes_inativos_90_pct",
        rule="PCCLIENT.DTULTCOMP há mais de 90 dias. O ERP rebaixa a classe em PRC_MED_CLASSEVENDA_CLIENTE (180 dias).",
        desc="Carteira adormecida para reativação.",
        calc="Clientes sem compra há mais de 90 dias divididos pela base com histórico de compra.",
        why="É a lista de reativação pronta para o vendedor. Antes de 180 dias o WinThor ainda não rebaixa a classe do cliente."),
    kpi("BLOQ_CLI", "Clientes bloqueados", C, PC, "clientes_bloqueados_pct",
        rule="PCCLIENT.BLOQUEIO = S (bloqueio automático por título vencido: F_PCPREST_VENCIDA_BLOQUEIO, PCCOB.BLOQAUTOMATICO).",
        desc="Quanto da carteira está travada para vender.",
        calc="Clientes bloqueados divididos pelo total de clientes cadastrados.",
        why="Cliente bloqueado não compra: cada ponto aqui é faturamento travado por cobrança. Cobrar antes do bloqueio automático preserva a venda."),
    kpi("COBERTURA", "Cobertura da base", C, PC, "positivacao_pct_base",
        rule="Positivados ÷ base ativa de 90 dias.",
        desc="Quanto da carteira ativa foi atendida no mês.",
        calc="Clientes positivados no mês divididos pelos clientes ativos nos últimos 90 dias.",
        why="Mostra se a equipe está visitando a carteira ou só atendendo quem liga."),
    kpi("RECOMPRA", "Recompra", C, PC, "recompra_pct",
        rule="Positivados que já eram clientes (DTPRIMCOMPRA anterior ao período).",
        desc="Fidelidade da base.",
        calc="Dos clientes que compraram no período, mostra a % que já era cliente antes.",
        why="Recompra alta é carteira fiel; baixa demais indica que a venda depende de conquistar cliente novo todo mês."),
    kpi("CREDITO", "Crédito disponível na carteira", C, PF, requer=["PCLIMCRED", "PCCOB.VALIDALIMITECREDITO"],
        rule="PKG_LIMITECREDITO.RETORNA_LIMITE_CRED_DISPONIVEL: LIMCRED + extra + sazonal − CR aberto − pedidos a faturar − cheques.",
        desc="Espaço de crédito que a carteira ainda tem.",
        calc="Soma, cliente a cliente, o limite de crédito menos o que já está em aberto e os pedidos a faturar — a mesma conta que o ERP faz ao liberar um pedido.",
        why="Crédito esgotado trava pedidos. Saber antes permite ajustar limite ou cobrar para liberar espaço.",
        unit="R$", polarity="maior_melhor", aggregation="ultimo"),
    kpi("CASHBACK", "Cashback a expirar", C, PC, requer=["PCCRECLI"],
        rule="PCCRECLI.CASHBACK = S com DTVALIDADECASHBACK próxima; PRC_INT_C5_BAIXACREDEXP cancela no vencimento.",
        desc="Crédito de cliente que vai vencer sem uso.",
        calc="Soma os créditos de cashback com validade nos próximos dias.",
        why="Cashback expirado é promessa não cumprida: avisar o cliente gera um pedido e evita atrito.",
        unit="R$", polarity="menor_melhor", aggregation="ultimo"),

    # -------------------------------------------------------------- FINANCEIRO
    kpi("MARGEM", "Margem bruta", F, PF, "margem_bruta_pct", "margemprev", tags=[DIR],
        rule="PCMOV: (venda − CUSTOFIN) ÷ venda. Qual custo vale é parâmetro (CON_SUGVENDA; ORIGEMCUSTOATUFAT define a filial). Meta: PCMETA.MARGEMPREV / PCFINANC.MARGEMPREV.",
        desc="Quanto sobra da venda depois do custo da mercadoria.",
        calc="Para cada item vendido, subtrai o custo da mercadoria do valor de venda; divide a soma pelo valor vendido.",
        why="É o indicador que decide se a empresa ganha ou perde dinheiro ao vender. Um ponto de margem numa distribuidora vale mais que dez pontos de volume."),
    kpi("LUCRO", "Lucro bruto", F, PF, "lucro_bruto", tags=[DIR],
        rule="Venda − custo financeiro nos itens faturados (PCMOV).",
        desc="Margem em reais.",
        calc="Valor vendido menos o custo da mercadoria vendida no período.",
        why="É o que a operação gerou para pagar despesas, impostos e sobrar resultado."),
    kpi("MARKUP", "Markup", F, PF, "markup_pct",
        rule="(venda − custo) ÷ custo nos itens faturados.",
        desc="Quanto se acrescenta sobre o custo.",
        calc="Diferença entre venda e custo dividida pelo custo.",
        why="É a linguagem do setor de compras e precificação: markup médio abaixo do previsto indica tabela desatualizada."),
    kpi("CMV", "CMV", F, PF, "cmv",
        rule="PCMOV.CUSTOFIN × QT nas operações de venda — o CMV gerencial de PKG_ESTOQUE.PRIV_ATUALIZAR_CUSTO.",
        desc="Custo da mercadoria vendida.",
        calc="Soma o custo dos itens vendidos no período.",
        why="Junto com o faturamento forma a margem. CMV subindo mais que a venda é custo de compra escapando."),
    kpi("DESP", "Despesas por competência", F, PF, "despesas_competencia",
        rule="PCLANC não canceladas por DTCOMPETENCIA (visão de DRE).",
        desc="Gasto do mês, pago ou não.",
        calc="Soma as contas a pagar lançadas com competência no período, tenham sido pagas ou não.",
        why="Visão de DRE: mostra o custo do mês mesmo que o pagamento caia no mês seguinte."),
    kpi("DESP_PCT", "Despesas sobre faturamento", F, PF, "despesas_pct_faturamento", tags=[DIR],
        rule="Despesas por competência ÷ faturamento.",
        desc="Peso da estrutura sobre a venda.",
        calc="Despesas do mês divididas pelo faturamento do mês.",
        why="Se cresce enquanto a venda cai, a estrutura está pesada para o tamanho atual do negócio."),
    kpi("FOLHA", "Folha sobre faturamento", F, PF, "folha_pct_faturamento",
        rule="PCLANC.TIPOSERVICO = 30 (salários) por competência ÷ faturamento.",
        desc="Custo de pessoal relativo.",
        calc="Lançamentos de salários do mês divididos pelo faturamento.",
        why="Referência para decidir contratação: a folha só pode crescer se a venda por funcionário também crescer."),
    kpi("RESULT", "Resultado operacional (aprox.)", F, PF, "resultado_operacional", tags=[DIR],
        rule="Lucro bruto − despesas por competência.",
        desc="Aproximação do resultado antes de impostos e financeiro.",
        calc="Lucro bruto menos as despesas do mês por competência.",
        why="Mostra se a operação se paga. É aproximado porque não separa impostos, depreciação e resultado financeiro."),
    kpi("RESULT_PCT", "Margem operacional (aprox.)", F, PF, "resultado_operacional_pct", tags=[DIR],
        rule="Resultado operacional ÷ faturamento.",
        desc="Quanto da venda vira resultado.",
        calc="Resultado operacional dividido pelo faturamento.",
        why="Permite comparar meses de tamanhos diferentes e a empresa com o setor."),
    kpi("RECEB", "Recebimentos", F, PF, "recebido",
        rule="PCPREST.DTPAG no mês (VPAGO).",
        desc="Dinheiro que entrou de clientes.",
        calc="Soma os títulos de clientes baixados (pagos) no período.",
        why="Recebimento abaixo do faturamento de prazo médio atrás indica atraso acumulando."),
    kpi("PAGOS", "Pagamentos", F, PF, "despesas_pagas",
        rule="PCLANC.DTPAGTO no mês (VPAGO).",
        desc="Dinheiro que saiu para fornecedores e despesas.",
        calc="Soma as contas a pagar baixadas (pagas) no período.",
        why="Junto com os recebimentos dá o fluxo de caixa realizado."),
    kpi("ENTR_CX", "Entradas de caixa", F, PF, "entradas_caixa",
        rule="PCMOVCR TIPO = D (créditos) sem estorno.",
        desc="Entradas reais no extrato.",
        calc="Soma os créditos lançados nas contas bancárias e caixas no período.",
        why="É o dinheiro que efetivamente entrou, independente de qual título gerou."),
    kpi("SAIDA_CX", "Saídas de caixa", F, PF, "saidas_caixa",
        rule="PCMOVCR TIPO = C (débitos) sem estorno.",
        desc="Saídas reais no extrato.",
        calc="Soma os débitos lançados nas contas bancárias e caixas no período.",
        why="Saída maior que entrada por vários meses consome o caixa mesmo com lucro no papel."),
    kpi("GERCX", "Geração de caixa", F, PF, "geracao_caixa", tags=[DIR],
        rule="Entradas − saídas do extrato (PCMOVCR).",
        desc="Caixa gerado no período.",
        calc="Entradas menos saídas do extrato bancário no período.",
        why="Lucro é opinião, caixa é fato: empresa lucrativa quebra por caixa negativo prolongado."),
    kpi("CAIXA", "Saldo de caixa e bancos", F, PF, "saldo_caixa", tags=[DIR],
        rule="PCFINANC: SALDOCX + SALDOBCO + SALDOAPLI da última fotografia (ATUALIZACAO_DIARIA); fallback PCESTCR.",
        desc="Disponibilidade financeira do dia.",
        calc="Soma o saldo em caixa, bancos e aplicações na última fotografia diária do financeiro.",
        why="Quantos dias de operação a empresa aguenta. Compare com o que vence nos próximos 30 dias."),
    kpi("POSLIQ", "Posição líquida (SALDOREAL)", F, PF, "posicao_liquida_financeira",
        rule="PCFINANC.SALDOREAL: caixa + bancos + a receber − a pagar, fotografado pelo fechamento diário.",
        desc="O boletim financeiro em um número.",
        calc="Caixa e bancos, mais o que há a receber, menos o que há a pagar, na última fotografia diária.",
        why="É a foto do patrimônio financeiro de curto prazo. Tendência de queda por semanas seguidas pede ação antes de faltar caixa."),
    kpi("CR", "Contas a receber em aberto", F, PF, "a_receber_aberto",
        rule="PCPREST com DTPAG e DTCANCEL nulas (índice canônico PCPREST_IDX83).",
        desc="Quanto os clientes devem.",
        calc="Soma os títulos de clientes ainda não pagos nem cancelados.",
        why="É capital da empresa na mão do cliente. Cresce com prazo longo e com inadimplência."),
    kpi("CR_VENC", "A receber vencido", F, PF, "a_receber_vencido", tags=[DIR],
        rule="PCPREST em aberto com DTVENC anterior à data. O ERP conta atraso em DIAS FINANCEIROS (F_QTDIASVENCIDOS, PCDIASUTEIS).",
        desc="Carteira atrasada.",
        calc="Soma os títulos em aberto cujo vencimento já passou.",
        why="É a fila de cobrança. Quanto mais velho o atraso, menor a chance de receber."),
    kpi("INAD", "Inadimplência (+30 dias)", F, PF, "inadimplencia_pct", tags=[DIR],
        rule="Vencido há mais de 30 dias ÷ total em aberto. Meta possível em PCMETA.PERINADIMPPREV.",
        desc="Parcela da carteira em risco.",
        calc="Títulos vencidos há mais de 30 dias divididos pelo total em aberto.",
        why="É o indicador de risco de crédito. Acima de 5% costuma exigir revisão de limites e de política de bloqueio."),
    kpi("CR60", "Carteira vencida há +60 dias", F, PF, "a_receber_vencido_60_pct",
        rule="Vencido há mais de 60 dias ÷ total em aberto.",
        desc="Envelhecimento da carteira.",
        calc="Títulos vencidos há mais de 60 dias divididos pelo total em aberto.",
        why="Passados 60 dias a cobrança interna perde força: é a fatia candidata a protesto ou negociação."),
    kpi("PMR", "Prazo médio de recebimento", F, PF, "prazo_medio_recebimento",
        rule="DTPAG − DTEMISSAO ponderado por valor nos títulos pagos. Meta possível em PCMETA.PRAZOMEDIOPREV.",
        desc="Dias que o dinheiro leva para entrar.",
        calc="Dias entre a emissão e o pagamento dos títulos pagos no período, ponderados pelo valor.",
        why="Cada dia a mais de prazo é capital de giro que a empresa financia. Compare com o prazo médio de pagamento aos fornecedores."),
    kpi("DSO", "DSO (dias de venda em aberto)", F, PF, "dso_dias",
        rule="A receber em aberto ÷ faturamento dos últimos 90 dias × 90.",
        desc="Quantos dias de venda estão na rua.",
        calc="Contas a receber em aberto divididas pela venda média diária dos últimos 90 dias.",
        why="Se o prazo concedido é 28 dias e o DSO é 45, a carteira está atrasando na média."),
    kpi("NOPRAZO", "Títulos pagos no prazo", F, PC, "titulos_pagos_no_prazo_pct",
        rule="DTPAG ≤ DTVENC nos títulos baixados no mês.",
        desc="Disciplina de pagamento da carteira.",
        calc="Dos títulos pagos no mês, mostra a % paga até o vencimento.",
        why="Base para decidir quem merece mais prazo e quem precisa de cobrança antecipada."),
    kpi("ATRASO", "Atraso médio dos recebimentos", F, PF, "atraso_medio_recebimento_dias",
        rule="DTPAG − DTVENC nos títulos pagos com atraso, ponderado por valor.",
        desc="Quanto o atrasado atrasa.",
        calc="Dias além do vencimento nos títulos pagos com atraso, ponderados pelo valor.",
        why="Diferencia atraso de poucos dias, que a régua de cobrança resolve, de atraso crônico."),
    kpi("MULTA", "Multa e juros recebidos", F, PF, "multa_juros_recebidos",
        rule="PCPREST.VALORMULTA nas baixas do mês; o detalhe fica em PCRECEBIMENTOJUROSDESCONTO.",
        desc="Receita financeira de cobrança.",
        calc="Soma a multa e os juros cobrados nos títulos pagos no período.",
        why="Multa não cobrada em título atrasado é receita deixada na mesa e incentivo ao atraso."),
    kpi("CR30", "A receber nos próximos 30 dias", F, PF, "a_receber_proximos_30_dias",
        rule="PCPREST em aberto com DTVENC nos 30 dias seguintes.",
        desc="Entrada prevista de curto prazo.",
        calc="Soma os títulos em aberto que vencem nos próximos 30 dias.",
        why="É a previsão de caixa do mês que vem, antes de qualquer atraso."),
    kpi("CP", "Contas a pagar em aberto", F, PF, "a_pagar_aberto",
        rule="PCLANC com DTPAGTO e DTCANCEL nulas e LANCEXCLUIDO = N (VIEW_CONTAS_A_PAGAR).",
        desc="Compromissos assumidos.",
        calc="Soma as contas a pagar ainda não pagas nem canceladas.",
        why="Contra o contas a receber e o caixa, mostra se a empresa consegue honrar o que deve."),
    kpi("CP_VENC", "A pagar vencido", F, PF, "a_pagar_vencido",
        rule="PCLANC em aberto com DTVENC anterior à data.",
        desc="Compromissos atrasados.",
        calc="Soma as contas a pagar em aberto cujo vencimento já passou.",
        why="Atraso com fornecedor custa juros, perda de prazo e de prioridade de entrega."),
    kpi("CP_VENC_PCT", "Contas a pagar vencidas", F, PF, "a_pagar_vencido_pct",
        rule="Vencido ÷ total a pagar em aberto.",
        desc="Saúde do contas a pagar.",
        calc="Contas vencidas divididas pelo total a pagar em aberto.",
        why="Mostra se o atraso é pontual ou se a empresa está rolando dívida com fornecedores."),
    kpi("CP30", "A pagar nos próximos 30 dias", F, PF, "a_pagar_proximos_30_dias",
        rule="PCLANC em aberto com DTVENC nos 30 dias seguintes.",
        desc="Saída prevista de curto prazo.",
        calc="Soma as contas a pagar que vencem nos próximos 30 dias.",
        why="Comparado ao caixa mais o que há a receber no mesmo prazo, antecipa a necessidade de capital."),
    kpi("PMP", "Prazo médio de pagamento", F, PF, "prazo_medio_pagamento",
        rule="DTPAGTO − DTEMISSAO ponderado por valor nas contas a pagar baixadas.",
        desc="Prazo que a empresa obtém dos fornecedores.",
        calc="Dias entre a emissão e o pagamento das contas pagas no período, ponderados pelo valor.",
        why="Prazo de pagamento maior que o de recebimento significa que o fornecedor financia a operação; o contrário consome caixa."),
    kpi("LIQ", "Liquidez (CR ÷ CP)", F, PF, "liquidez_cr_cp",
        rule="A receber em aberto ÷ a pagar em aberto.",
        desc="Cobertura dos compromissos pelos recebíveis.",
        calc="Contas a receber em aberto divididas pelas contas a pagar em aberto.",
        why="Abaixo de 1 a empresa deve mais do que tem a receber: o caixa passa a depender de venda futura."),
    kpi("BLOQ_IMIN", "Clientes com bloqueio iminente", F, PC, requer=["PCDIASUTEIS", "PCCOB"],
        rule="Régua de ATUALIZACAO_DIARIA/P_PC_BLOQUEARCLIENTE: título vencido + carência (PCCOB.NUMDIASBLOQAUTOMATIC, DIASCARENCIA) em dias financeiros.",
        desc="Clientes que o bloqueio automático vai atingir.",
        calc="Aplica a mesma régua do WinThor (vencimento mais carência, em dias úteis financeiros) e conta os clientes que serão bloqueados no próximo fechamento.",
        why="Cobrar hoje evita o bloqueio de amanhã e a venda perdida da semana.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("PRORROG", "Títulos prorrogados", F, PF, requer=["PCPREST.DTVENCANTERIOR", "PCDESDLANC"],
        rule="PCPREST.DTVENCANTERIOR preenchida e cadeias de desdobramento em PCDESDLANC.",
        desc="Dias ganhos por prorrogação, por cliente e operador.",
        calc="Conta os títulos que tiveram o vencimento adiado no período.",
        why="Prorrogação em excesso esconde inadimplência e costuma se concentrar em poucos operadores.",
        unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),
    kpi("DESC_BAIXA", "Desconto concedido na baixa", F, PF, requer=["PCRECEBIMENTOJUROSDESCONTO"],
        rule="PCRECEBIMENTOJUROSDESCONTO.VALORDESC por operador (PKG_FINANCEIRO).",
        desc="Receita cedida no ato do recebimento.",
        calc="Soma os descontos dados na hora de baixar títulos.",
        why="Desconto na baixa é margem indo embora depois da venda fechada; precisa de alçada.",
        unit="R$", polarity="menor_melhor", aggregation="soma"),
    kpi("DUPLA_ASSIN", "Títulos a pagar sem dupla autorização", F, PP, requer=["PCLANC.CODFUNCAUTOR1", "PCLANC.CODFUNCAUTOR2"],
        rule="PCLANC com CODFUNCAUTOR1/2 vazios e DTVENC próxima.",
        desc="Pagamentos que vão vencer sem alçada completa.",
        calc="Conta as contas a pagar próximas do vencimento que ainda não receberam as duas autorizações.",
        why="Evita pagamento sem aprovação e, ao mesmo tempo, atraso por falta de assinatura.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("ADIANT_FORN", "Adiantamentos a fornecedor em aberto", F, PF, requer=["PCLANC.ADIANTAMENTO", "PCLANC.VLRUTILIZADOADIANTFORNEC"],
        rule="PCLANC.ADIANTAMENTO − VLRUTILIZADOADIANTFORNEC.",
        desc="Dinheiro adiantado e ainda não consumido.",
        calc="Soma os adiantamentos feitos a fornecedores que ainda não foram abatidos em nota.",
        why="É caixa parado fora da empresa; fornecedor com adiantamento antigo precisa de cobrança.",
        unit="R$", polarity="menor_melhor", aggregation="ultimo"),

    # ----------------------------------------------------------------- ESTOQUE
    kpi("ESTQ", "Estoque a custo", E, PF, "estoque_valor", tags=[DIR],
        rule="PCEST.QTESTGER × CUSTOREAL (custo médio por filial; VLCUSTOREAL não existe na PCEST).",
        desc="Capital imobilizado em mercadoria.",
        calc="Multiplica o saldo de cada produto pelo custo médio e soma tudo.",
        why="É o maior ativo de uma distribuidora. Compare com a cobertura em dias para saber se está alto por venda ou por excesso."),
    kpi("ESTQ_FIN", "Estoque financeiro (PCFINANC)", E, PF, "estoque_financeiro_foto",
        rule="PCFINANC.SALDOESTFIN da fotografia diária.",
        desc="O estoque como o financeiro enxerga.",
        calc="Valor do estoque registrado na fotografia diária do financeiro do WinThor.",
        why="Serve de conferência com o estoque a custo calculado item a item."),
    kpi("COBERT", "Cobertura de estoque", E, PP, "cobertura_estoque_dias", tags=[DIR],
        rule="Disponível ÷ PCEST.QTGIRODIA (giro oficial de VENDAS.CALCULARGIRODIA), ponderado por custo. Alvo por item em PCEST.ESTIDEAL.",
        desc="Dias de venda que o estoque cobre.",
        calc="Divide o estoque disponível pela venda média diária de cada produto e pondera pelo valor a custo.",
        why="Cobertura alta é dinheiro parado; baixa é ruptura. O ideal varia por produto e prazo de reposição."),
    kpi("RUPT", "Ruptura", E, PC, "ruptura_pct", tags=[DIR],
        rule="Itens com giro e disponível ≤ 0 (QTESTGER − QTRESERV − QTBLOQUEADA, régua de PKG_REPOSICAOLOJAS).",
        desc="Falta de produto com demanda.",
        calc="Dos produtos que têm venda no mês, mostra a % que está sem estoque disponível.",
        why="Ruptura é venda perdida silenciosa: o cliente compra do concorrente e o pedido nem chega a ser digitado."),
    kpi("GIRO", "Giro de estoque", E, PP, "giro_estoque",
        rule="CMV do mês ÷ estoque a custo.",
        desc="Velocidade com que o estoque se renova.",
        calc="Custo da mercadoria vendida no mês dividido pelo estoque a custo.",
        why="Giro maior significa menos capital para o mesmo faturamento."),
    kpi("VPERD", "Venda perdida por falta", E, PC, "venda_perdida_qtd",
        rule="PCEST.QTVENDAPERDIDA (o ERP acumula na venda sem estoque).",
        desc="Unidades que deixaram de ser vendidas.",
        calc="Soma as unidades que o WinThor registrou como venda perdida por falta de estoque.",
        why="Quantifica o custo da ruptura e prioriza a reposição pelo que mais faltou."),
    kpi("CAP_PARADO", "Capital parado", E, PF, "capital_parado",
        rule="PCEST com saldo e QTVENDMES = 0, a custo. Ver também FIMESTOQUE.",
        desc="Mercadoria que não gira.",
        calc="Soma o valor a custo dos produtos com estoque e sem nenhuma venda no mês.",
        why="É o primeiro lugar para buscar caixa: promoção, devolução ao fornecedor ou fim de linha."),
    kpi("CAP_PARADO_PCT", "Capital parado sobre o estoque", E, PF, "capital_parado_pct",
        rule="Capital parado ÷ estoque a custo.",
        desc="Parcela do estoque sem giro.",
        calc="Capital parado dividido pelo estoque total a custo.",
        why="Acima de 10% do estoque sem giro indica compra desalinhada da venda."),
    kpi("SEM_GIRO", "Itens sem giro", E, PP, "itens_sem_giro_pct",
        rule="Itens com saldo e sem venda no mês ÷ itens com saldo.",
        desc="Amplitude do problema de giro.",
        calc="Produtos com estoque e sem venda no mês divididos pelos produtos com estoque.",
        why="Mostra se o capital parado está em poucos itens caros ou espalhado por todo o portfólio."),
    kpi("EXCESSO", "Excesso sobre o estoque máximo", E, PF, "excesso_estoque",
        rule="(QTESTGER − ESTMAX) × CUSTOREAL quando acima. ESTMAX = DIASESTOQUEMAX × QTGIRODIA quando automático.",
        desc="Compra além do necessário.",
        calc="Para cada produto acima do estoque máximo definido, soma o valor do que excede.",
        why="Excesso vira capital parado e, em perecíveis, perda. É o KPI para avaliar o comprador."),
    kpi("ABAIXO_MIN", "Itens abaixo do mínimo", E, PP, "abaixo_minimo_pct",
        rule="QTESTGER < ESTMIN nos itens com mínimo definido (gatilho de reposição).",
        desc="Risco de ruptura iminente.",
        calc="Dos produtos com estoque mínimo definido, mostra a % que está abaixo dele.",
        why="É a ruptura de amanhã: a lista de compra urgente."),
    kpi("SKUS", "SKUs com estoque", E, PP, "skus_com_estoque",
        rule="Produtos ativos com QTESTGER > 0.",
        desc="Portfólio disponível para vender.",
        calc="Conta os produtos ativos que têm saldo em estoque.",
        why="Portfólio disponível sustenta o mix vendido; se cai, o vendedor tem menos o que oferecer."),
    kpi("BLOQ_EST", "Estoque bloqueado", E, PF, "estoque_bloqueado",
        rule="PCEST.QTBLOQUEADA × custo (avaria/quarentena, MOTIVOBLOQESTOQUE).",
        desc="Mercadoria travada.",
        calc="Multiplica a quantidade bloqueada (avaria, quarentena) pelo custo e soma.",
        why="Estoque bloqueado não vende e ocupa espaço; precisa de decisão rápida entre liberar, trocar ou descartar."),
    kpi("VALIDADE", "Estoque a vencer em 30 dias", E, PF, requer=["PCLOTE"],
        rule="PCLOTE.DTVALIDADE nos próximos 30 dias × custo (FEFO do WMS; lote vencido devolve 0 em ESTOQUE_DISPONIVEL_LOTE_VENDA).",
        desc="Valor em risco por vencimento.",
        calc="Soma o valor a custo dos lotes com validade nos próximos 30 dias.",
        why="Produto vencido é perda total mais custo de descarte; com 30 dias ainda dá para vender com desconto.",
        unit="R$", polarity="menor_melhor", aggregation="ultimo"),
    kpi("INVENT", "Itens sem inventário há +90 dias", E, PP, requer=["PCEST.DTULTINVENT"],
        rule="PCEST.DTULTINVENT anterior a 90 dias.",
        desc="Aging de contagem.",
        calc="Dos produtos com estoque, mostra a % que não é contada há mais de 90 dias.",
        why="Estoque sem contagem é saldo de sistema, não saldo real. Divergência vira corte e ruptura fantasma.",
        unit="%", polarity="menor_melhor", aggregation="ultimo"),
    kpi("DIVERG_RECEB", "Divergências no recebimento", E, PP, requer=["PCNFENTPREENT", "PCMOVPREENT"],
        rule="PCMOVPREENT.QUALDIVERGENCIA na pré-entrada (rotina 1309).",
        desc="Conferência pedido × nota.",
        calc="Conta as divergências entre o pedido de compra e a nota recebida, item a item.",
        why="Divergência no recebimento é custo errado no estoque e briga com o fornecedor depois.",
        unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ----------------------------------------------------------------- COMPRAS
    kpi("COMPRAS", "Compras (entradas)", K, PF, "compras_valor",
        rule="PCNFENT por DTENT, agrupada por NUMTRANSENT (uma linha por conta contábil). Devoluções de cliente também entram na PCNFENT — filtrar por tipo.",
        desc="Quanto foi comprado de fornecedores.",
        calc="Soma o valor das notas de entrada de fornecedores no período.",
        why="Compra acima da venda por meses seguidos vira excesso de estoque; abaixo, ruptura."),
    kpi("NF_ENT", "Notas de entrada", K, PP, "qtd_notas_entrada",
        rule="Contagem de PCNFENT no mês.",
        desc="Volume de recebimentos.",
        calc="Conta as notas de entrada recebidas no período.",
        why="Muitas notas pequenas sobrecarregam o recebimento; poucas grandes concentram risco."),
    kpi("FORN_ATIVOS", "Fornecedores com compra", K, PP, "fornecedores_ativos",
        rule="CODFORNEC distintos com nota no mês.",
        desc="Amplitude da base de fornecimento.",
        calc="Conta os fornecedores diferentes com nota de entrada no período.",
        why="Base ampla dá poder de negociação e reduz dependência."),
    kpi("COMPRA_MEDIA", "Compra média por nota", K, PF, "compra_media_por_nota",
        rule="PCNFENT.VLTOTAL médio.",
        desc="Tamanho médio do lote comprado.",
        calc="Valor comprado dividido pelo número de notas de entrada.",
        why="Lotes maiores dão preço melhor, mas aumentam estoque e prazo de giro."),
    kpi("COMPRAS_PCT", "Compras sobre faturamento", K, PF, "compras_pct_faturamento",
        rule="Entradas ÷ faturamento.",
        desc="Ritmo de compra contra a venda.",
        calc="Valor comprado dividido pelo faturamento do mês.",
        why="Numa distribuidora saudável fica próximo do CMV sobre a venda; muito acima é estoque crescendo."),
    kpi("TOP5_FORN", "Concentração nos 5 maiores fornecedores", K, PP, "concentracao_top5_fornecedores_pct",
        rule="Fatia das compras nos 5 maiores CODFORNEC.",
        desc="Dependência de fornecedores.",
        calc="Compras dos 5 maiores fornecedores divididas pelo total comprado.",
        why="Alta concentração é natural em distribuição exclusiva, mas reduz o poder de negociação."),
    kpi("FRETE_COMPRA", "Frete sobre compras", K, PF, "frete_compras_pct",
        rule="PCNFENT.VLFRETE ÷ VLTOTAL.",
        desc="Custo logístico de entrada.",
        calc="Frete das notas de entrada dividido pelo valor comprado.",
        why="Frete de entrada faz parte do custo do produto e muda a margem real."),
    kpi("PED_COMPRA_ATRASO", "Pedidos de compra atrasados", K, PP, requer=["PCPEDIDO", "PCITEM"],
        rule="PCPEDIDO.DTPREVENT vencida com saldo a entregar.",
        desc="Fornecedor atrasando a reposição.",
        calc="Conta os pedidos de compra com data prevista vencida e saldo ainda por entregar.",
        why="Atraso do fornecedor vira ruptura na ponta; acompanhar por fornecedor sustenta a negociação.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("CUSTO_SUBIU", "Itens com custo de entrada acima da média", K, PF, requer=["PCCONSOLIDAMES"],
        rule="PCEST.CUSTOULTENT vs PCCONSOLIDAMES.VLULTENTMES (11 meses, FUNCOESCOMPRAS).",
        desc="Sentinela de custo de entrada.",
        calc="Compara o custo da última entrada de cada produto com a média dos últimos meses e conta os que subiram.",
        why="Aumento de custo não repassado ao preço come a margem sem ninguém perceber.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("VERBA", "Verba de fornecedor a receber", K, PF, requer=["PCVERBA", "PCESTCRFOR"],
        rule="PCVERBA / PCMOVCRFOR / PCESTCRFOR — o dinheiro do fornecedor.",
        desc="Verba negociada ainda não recebida.",
        calc="Soma as verbas acordadas com fornecedores que ainda não entraram.",
        why="Verba é margem negociada; não cobrada, é margem perdida.",
        unit="R$", polarity="maior_melhor", aggregation="ultimo"),

    # --------------------------------------------------------------- LOGÍSTICA
    kpi("CARGAS", "Cargas expedidas", L, PP, "cargas_expedidas",
        rule="PCCARREG com DTSAIDA no período e DT_CANCEL nula (a tabela não tem POSICAO).",
        desc="Volume de expedição.",
        calc="Conta os carregamentos que saíram para entrega no período.",
        why="Base para produtividade da frota e custo por entrega."),
    kpi("NFCARGA", "Notas por carga", L, PP, "notas_por_carga",
        rule="PCCARREG.NUMNOTAS ÷ cargas.",
        desc="Densidade de entrega.",
        calc="Notas transportadas divididas pelo número de cargas.",
        why="Mais notas por carga é frete diluído; poucas é veículo saindo vazio."),
    kpi("TON", "Peso entregue", L, PP, "peso_entregue_ton",
        rule="PCCARREG.TOTPESO somado, em toneladas.",
        desc="Volume físico movimentado.",
        calc="Soma o peso das cargas expedidas, em toneladas.",
        why="Mede a operação física, útil para dimensionar frota e equipe."),
    kpi("FRETE", "Frete sobre faturamento", L, PF, "frete_pct_faturamento", tags=[DIR],
        rule="PCCARREG.VLFRETE ÷ faturamento.",
        desc="Peso do custo de entrega.",
        calc="Custo de frete das cargas dividido pelo faturamento.",
        why="É o principal custo logístico; sobe quando a venda pulveriza ou as rotas ficam longas."),
    kpi("VL_CARGA", "Valor médio por carga", L, PF, "valor_medio_por_carga",
        rule="PCCARREG.VLTOTAL médio (totais oficiais vêm de PCNFSAID, excluindo transferências).",
        desc="Valor por viagem.",
        calc="Valor entregue dividido pelo número de cargas.",
        why="Carga de baixo valor com o mesmo custo de viagem derruba a margem da entrega."),
    kpi("KG_CARGA", "Peso médio por carga", L, PP, "peso_medio_por_carga_kg",
        rule="PCCARREG.TOTPESO médio.",
        desc="Ocupação do veículo.",
        calc="Peso total dividido pelo número de cargas.",
        why="Compare com a capacidade dos veículos: ocupação baixa é frete caro."),
    kpi("ROTA_DIAS", "Tempo médio em rota", L, PP, "tempo_medio_rota_dias",
        rule="DTRETORNO − DTSAIDA das cargas que retornaram.",
        desc="Duração da viagem.",
        calc="Dias entre a saída e o retorno das cargas, em média.",
        why="Rota mais longa que o previsto atrasa a entrega e o acerto financeiro."),
    kpi("EM_ROTA", "Cargas em rota", L, PP, "cargas_em_rota",
        rule="DTSAIDA preenchida e DTRETORNO nula.",
        desc="Veículos na rua agora.",
        calc="Conta as cargas que saíram e ainda não retornaram.",
        why="Carga na rua além do prazo é entrega atrasada e dinheiro sem acerto."),
    kpi("CARGA_CANC", "Cargas canceladas", L, PP, "cargas_canceladas_pct",
        rule="PCCARREG.DT_CANCEL preenchida ÷ cargas do período.",
        desc="Retrabalho na expedição.",
        calc="Cargas canceladas divididas pelas cargas do período.",
        why="Cancelamento de carga é separação refeita e entrega adiada."),
    kpi("FRETE_KG", "Frete por kg", L, PF, "custo_frete_por_kg",
        rule="VLFRETE ÷ TOTPESO das cargas.",
        desc="Custo unitário de transporte.",
        calc="Custo de frete dividido pelo peso entregue.",
        why="Permite comparar rotas, veículos e transportadoras na mesma régua."),
    kpi("FRETE_NOTA", "Frete por nota entregue", L, PF, "custo_frete_por_nota",
        rule="VLFRETE ÷ NUMNOTAS das cargas.",
        desc="Custo por entrega.",
        calc="Custo de frete dividido pelo número de notas transportadas.",
        why="É o custo de cada entrega; pedido abaixo desse valor dá prejuízo na logística."),
    kpi("FAT_DIA", "Pedidos faturados no mesmo dia", L, PP, "pedidos_faturados_no_dia_pct",
        rule="PCPEDC.DTFAT = DATA.",
        desc="Agilidade do ciclo pedido → nota.",
        calc="Pedidos faturados no dia em que foram digitados divididos pelos pedidos faturados.",
        why="Faturar no mesmo dia é entregar no dia seguinte; é o KPI de nível de serviço interno."),
    kpi("CICLO_CARGA", "Ciclo da carga (montagem → saída)", L, PP, requer=["PCCARREG.DATAMON", "PCCARREG.DTFECHA", "PCCARREG.DATACONF"],
        rule="PCCARREG.DATAMON → DTFECHA → DATACONF → DTFAT → DTSAIDA (funil do ciclo, estudo L2).",
        desc="Horas entre montar a carga e o veículo sair.",
        calc="Mede o tempo entre a montagem da carga, o fechamento, a conferência, o faturamento e a saída.",
        why="Mostra em qual etapa a expedição perde tempo.",
        unit="h", polarity="menor_melhor", aggregation="media", decimals=1),
    kpi("KM", "Km rodados por carga", L, PP, "km_por_carga",
        rule="PCCARREG.KMFINAL − KMINICIAL no acerto (rotina 1207).",
        desc="Produtividade de frota.",
        calc="Quilômetros rodados por carga, a partir do odômetro registrado no acerto.",
        why="Km por entrega e por real vendido é a base para roteirizar melhor."),
    kpi("KM_ENTREGA", "Km por entrega", L, PP, "km_por_entrega",
        rule="(KMFINAL − KMINICIAL) ÷ NUMNOTAS nas cargas com odômetro.",
        desc="Distância percorrida por nota entregue.",
        calc="Quilômetros rodados divididos pelas notas entregues.",
        why="É o custo de rota em quilômetros; roteirizar bem derruba este número."),
    kpi("SEM_KM", "Cargas sem odômetro no acerto", L, PP, "cargas_sem_km_pct",
        rule="Cargas com DTRETORNO e KMFINAL vazio ou zero.",
        desc="Qualidade do acerto de carga.",
        calc="Cargas retornadas sem quilometragem registrada divididas pelas cargas retornadas.",
        why="Sem km no acerto não há custo de frota confiável; é disciplina do acerto."),
    kpi("ENTREGAS_CARGA", "Entregas por carga", L, PP, "entregas_por_carga", origem=O_ROTA,
        rule="PCCARREG.NUMENT = clientes distintos da carga (rotina 1743) — o mesmo NUMCLIENTES que o FusionTrak recebe, lido direto do WinThor.",
        desc="Densidade de entrega por viagem.",
        calc="Clientes atendidos por carga, em média.",
        why="Mais entregas por carga diluem o custo da viagem. Sai de qualquer WinThor, com ou sem roteirizador."),
    kpi("PRACAS_CARGA", "Praças por carga", L, PP, "cidades_por_carga_erp", origem=O_ROTA,
        rule="PCCARREG.NUMCID = praças distintas da carga — o NUMCIDADES do roteirizador, lido direto do WinThor.",
        desc="Dispersão geográfica da carga.",
        calc="Praças (regiões de entrega) atendidas por carga, em média.",
        why="Carga espalhada roda mais km por entrega. Sai de qualquer WinThor."),
    kpi("ATRASO_ENTREGA", "Cargas além do prazo de rota", L, PC, requer=["PCROTAEXP.PRAZOPREVENT"],
        rule="DTSAIDAVEICULO + PCROTAEXP.PRAZOPREVENT < hoje e DTRETORNO nula.",
        desc="Entregas atrasadas na rua.",
        calc="Conta as cargas que saíram e passaram do prazo previsto da rota sem retornar.",
        why="É a reclamação do cliente antes de ela chegar.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("OCORRENCIA", "Ocorrências de entrega", L, PC, requer=["FUSIONTRAK_INT_EVENTOS", "PCMENS"],
        rule="Eventos TIPO = 7 do FusionTrak viram PCMENS; devolução parcial/total por ocorrência.",
        desc="Problemas na entrega.",
        calc="Conta as ocorrências registradas na entrega (recusa, ausência, devolução parcial).",
        why="Ocorrência é entrega repetida: custo dobrado e cliente insatisfeito.",
        unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ------------------------------------------------------------------ FISCAL
    kpi("NFE_AUT", "NF-e autorizadas", X, PP, "nfe_autorizadas_pct",
        rule="PCNFSAID.SITUACAONFE = 100 sobre as notas com situação preenchida.",
        desc="Saúde da emissão fiscal.",
        calc="Notas autorizadas pela SEFAZ divididas pelas notas emitidas.",
        why="Nota não autorizada é mercadoria que não pode sair; mede a estabilidade do fiscal."),
    kpi("NF_CANC", "Notas canceladas", X, PP, "notas_canceladas_pct",
        rule="PCNFSAID.DTCANCEL preenchida (P_PC_CACELA_NF); detalhe em PCNFCAN.",
        desc="Retrabalho fiscal.",
        calc="Notas canceladas divididas pelas notas emitidas.",
        why="Cancelamento frequente indica erro de digitação, de preço ou de cadastro."),
    kpi("ICMS", "ICMS sobre faturamento", X, PF, "icms_pct_faturamento",
        rule="PCNFSAID.VLICMS ÷ VLTOTAL (PKG_TRIBUTACAO).",
        desc="Peso do ICMS.",
        calc="ICMS destacado nas notas dividido pelo faturamento.",
        why="Mudança brusca indica erro de tributação ou mudança de mix entre estados."),
    kpi("ST", "ICMS-ST sobre faturamento", X, PF, "st_pct_faturamento",
        rule="PCNFSAID.VLST ÷ VLTOTAL.",
        desc="Peso da substituição tributária.",
        calc="Substituição tributária das notas dividida pelo faturamento.",
        why="ST paga antecipadamente afeta o caixa; acompanhar evita surpresa na apuração."),
    kpi("IPI", "IPI sobre faturamento", X, PF, "ipi_pct_faturamento",
        rule="PCNFSAID.VLIPI ÷ VLTOTAL.",
        desc="Peso do IPI.",
        calc="IPI das notas dividido pelo faturamento.",
        why="Relevante para quem industrializa ou importa; variação sinaliza erro de classificação."),
    kpi("TRIB", "Carga tributária na saída", X, PF, "carga_tributaria_pct",
        rule="ICMS + ST + IPI ÷ faturamento.",
        desc="Tributos embutidos na venda.",
        calc="Soma ICMS, ST e IPI das notas e divide pelo faturamento.",
        why="Mostra quanto do preço é imposto e ajuda a precificar."),
    kpi("NF_DIA", "Notas por dia útil", X, PP, "notas_por_dia_util",
        rule="Notas faturadas ÷ dias úteis (seg–sex) do período.",
        desc="Ritmo diário de emissão.",
        calc="Notas do período divididas pelos dias úteis.",
        why="Ritmo estável facilita dimensionar faturamento, expedição e frota."),
    kpi("DENEGADA", "NF-e denegadas ou rejeitadas", X, PP, requer=["PCNFSAID.SITUACAONFE (110/205/301/302)"],
        rule="SITUACAONFE em 110/205/301/302; contingência em PKG_CONTINGENCIA_SVC.",
        desc="Notas que a SEFAZ recusou.",
        calc="Conta as notas denegadas ou rejeitadas pela SEFAZ no período.",
        why="Denegação costuma ser problema cadastral do cliente; resolvido cedo, a venda sai no mesmo dia.",
        unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),
    kpi("MDFE", "MDF-e pendentes de transmissão", X, PP, requer=["PCMANIFESTOELETRONICOC"],
        rule="PCMANIFESTOELETRONICOC.SITUACAOMDFE = 0 com UTILIZAMDFE = S na filial.",
        desc="Cargas sem manifesto.",
        calc="Conta os manifestos eletrônicos ainda não transmitidos.",
        why="Carga sem MDF-e é multa na fiscalização e caminhão parado.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("NUMERACAO", "Falhas de numeração de NF", X, PP, requer=["PCLOGALTERACAODADOS"],
        rule="PCLOGALTERACAODADOS com 'ERRO NA BUSCA NO PROXIMO NUMERO DE NOTA' (OBTERPROXIMONUMERONOTANFE).",
        desc="Erros de emissão em série.",
        calc="Conta os erros de numeração de nota registrados pelo WinThor.",
        why="Falha em série trava o faturamento na hora de pico; mostra problema de concorrência ou de configuração.",
        unit="un", polarity="menor_melhor", aggregation="soma", decimals=0),

    # ------------------------------------------------------------------ PESSOAS
    kpi("HC", "Headcount", R, PA, "headcount", tags=[DIR],
        rule="PCEMPR com ADMISSAO ≤ data e sem DTDEMISSAO (SITUACAO A).",
        desc="Tamanho da equipe.",
        calc="Conta os funcionários ativos no fim do período.",
        why="Base de todos os indicadores de produtividade por pessoa."),
    kpi("TURN", "Turnover", R, PA, "turnover_pct", tags=[DIR],
        rule="(admissões + demissões) ÷ 2 sobre o headcount.",
        desc="Rotatividade.",
        calc="Média entre admissões e demissões do mês dividida pelo número de funcionários.",
        why="Turnover alto custa treinamento, erro operacional e clima. Em vendas e logística pesa direto no serviço."),
    kpi("DESLIG", "Desligamentos", R, PA, "desligamentos",
        rule="PCEMPR.DTDEMISSAO no mês.",
        desc="Saídas.",
        calc="Conta os desligamentos do período.",
        why="Concentração de saídas em uma área aponta problema de gestão ou de carga de trabalho."),
    kpi("ADM", "Admissões", R, PA, "admissoes",
        rule="PCEMPR.ADMISSAO no mês.",
        desc="Entradas.",
        calc="Conta as admissões do período.",
        why="Admissão sem crescimento de venda é custo; compare com faturamento por funcionário."),
    kpi("CASA", "Tempo médio de casa", R, PA, "tempo_medio_casa_anos",
        rule="Média de anos desde ADMISSAO dos ativos.",
        desc="Retenção.",
        calc="Média de anos desde a admissão dos funcionários ativos.",
        why="Equipe experiente erra menos e atende melhor; queda brusca indica perda de gente antiga."),
    kpi("MOTORISTAS", "Motoristas ativos", R, PP, "motoristas_ativos",
        rule="PCEMPR.TIPOMOTORISTA preenchido e ativo (mesmo dado que alimenta o MyFrota).",
        desc="Capacidade de entrega própria.",
        calc="Conta os funcionários cadastrados como motoristas e ativos.",
        why="Limita quantas cargas saem por dia; compare com cargas expedidas."),
    kpi("FAT_FUNC", "Faturamento por funcionário", R, PF, "faturamento_por_funcionario",
        rule="Faturamento ÷ headcount.",
        desc="Produtividade da empresa.",
        calc="Faturamento do mês dividido pelo número de funcionários ativos.",
        why="É a medida mais simples de eficiência da estrutura; deve crescer com o tempo."),
    kpi("CNH", "CNH de motorista vencendo em 30 dias", R, PP, requer=["PCEMPR.DTVALIDADECNH"],
        rule="PCEMPR.DTVALIDADECNH nos próximos 30 dias.",
        desc="Risco operacional e legal.",
        calc="Conta os motoristas com habilitação vencendo nos próximos 30 dias.",
        why="Motorista sem CNH válida é carga parada e multa; renovar leva semanas.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),
    kpi("USUARIO_DESLIG", "Usuários ativos de funcionários desligados", R, PP, requer=["PCEMPR.DTDEMISSAO x PCEMPR.USUARIOBD"],
        rule="PCEMPR com DTDEMISSAO e usuário ainda habilitado (ver PCLOGUSUARIO).",
        desc="Brecha de segurança.",
        calc="Conta os funcionários desligados que ainda têm usuário ativo no sistema.",
        why="Acesso de ex-funcionário é risco de fraude e de vazamento; deve ser zero.",
        unit="un", polarity="menor_melhor", aggregation="ultimo", decimals=0),

    # --------------------------------------------------- FORÇA DE VENDAS (Ion / MaxSoluções)
    # O que o app do vendedor apura: aprendido do SQL que a Ion (IONV_SYNC.IONVD_*) e a
    # MaxSoluções (MAXSOLUCOES.PCMXS*) executam no WinThor. Não precisa do app instalado:
    # a regra lê as mesmas tabelas do ERP (PCPEDC, PCNFSAID, PCMOV, PCPREST, PCCLIENT).
    kpi("FV_TRANSMITIDA", "Venda transmitida", FV, PF, "valor_pedidos", origem=O_FV,
        rule="Ion IONVD_VENDEDOR_PERFORMANCE.VL_VENDA_TRANSMITIDA: SUM(PCPEDC.VLATEND) com CONDVENDA fora de 5/6/11/12 (bonificação), por vendedor e dia.",
        desc="O que a equipe digitou de pedidos, antes de faturar.",
        calc="Soma o valor dos pedidos digitados no período, sem bonificações.",
        why="É a venda no momento em que o vendedor a fez. A diferença para o faturado mostra o que ficou preso em bloqueio, corte ou carga."),
    kpi("FV_BLOQUEADA", "Venda bloqueada", FV, PP, "pedidos_bloqueados_valor", origem=O_FV,
        rule="Ion VL_VENDA_BLOQUEADA: PCPEDC.POSICAO = 'B' (PKG_MOTIVOBLOQUEIO). Nosso espelho guarda POSICAO em Order.erp_position.",
        desc="Pedidos parados em bloqueio.",
        calc="Soma o valor dos pedidos pendentes que estão bloqueados.",
        why="É venda feita que não vira entrega enquanto alguém não libera; o vendedor vê no app e cobra a liberação."),
    kpi("FV_BLOQ_PCT", "Pedidos bloqueados", FV, PP, "pedidos_bloqueados_pct", origem=O_FV,
        rule="Pedidos com POSICAO = 'B' sobre os digitados no período.",
        desc="Quanto do que a equipe digita cai em bloqueio.",
        calc="Pedidos bloqueados divididos pelos pedidos digitados.",
        why="Bloqueio recorrente é limite de crédito curto ou política de preço apertada; olhar por vendedor mostra quem força a régua."),
    kpi("FV_COMISSAO", "Comissão gerada", FV, PF, "comissao_valor", origem=O_FV,
        rule="Ion VL_COMISSAO_VENDA: PCMOV.PERCOM × valor do item; a faixa por desconto vem de PCCOMISSAOUSUR (FUNCOESVENDAS).",
        desc="Quanto a venda do período gera de comissão.",
        calc="Aplica o percentual de comissão de cada item vendido ao valor do item e soma.",
        why="É a previsão da folha comercial; comissão crescendo mais que a margem indica desconto sendo pago duas vezes."),
    kpi("FV_COMISSAO_PCT", "Comissão sobre a venda", FV, PF, "comissao_pct", origem=O_FV,
        rule="Comissão gerada ÷ valor vendido nos itens.",
        desc="Peso da comissão sobre a venda.",
        calc="Comissão gerada dividida pelo valor vendido.",
        why="Referência para política comercial: comissão por faixa de desconto deve cair quando o desconto sobe."),
    kpi("FV_ABC_CLI", "Clientes curva A", FV, PC, "clientes_curva_a_pct", origem=O_FV,
        rule="Ion IONVD_ABC_CLIENTES: RANK() e RATIO_TO_REPORT(SUM(VLTOTGER)) sobre PCNFSAID por vendedor; curva A = quem soma 80 % da venda.",
        desc="Quantos clientes carregam 80 % da venda.",
        calc="Ordena os clientes pela venda do período e conta quantos são necessários para chegar a 80 % do total; mostra em % da base positivada.",
        why="Se 10 % dos clientes fazem 80 % da venda, a carteira é frágil: perder um cliente A dói mais que perder dez C."),
    kpi("FV_ABC_PROD", "Produtos curva A", FV, PP, "skus_curva_a_pct", origem=O_FV,
        rule="Ion IONVD_ABC_PRODUTOS: mesma régua da curva de clientes, sobre PCMOV por produto.",
        desc="Quantos produtos carregam 80 % da venda.",
        calc="Ordena os produtos pela venda do período e conta quantos somam 80 % do total; mostra em % do mix vendido.",
        why="Itens A não podem faltar nunca; itens C são candidatos a sair de linha."),
    kpi("FV_MIX_CLI", "Mix por cliente", FV, PC, "mix_por_cliente", origem=O_FV,
        rule="MaxSoluções PCMXSMIXCLIENTES / Ion IONVD_POSITIVACAO_PRODUTOS: produtos distintos comprados por cliente no período.",
        desc="Quantos produtos diferentes cada cliente compra.",
        calc="Para cada cliente positivado, conta os produtos diferentes comprados; mostra a média.",
        why="É o KPI da venda cruzada: o app do vendedor sugere o que o cliente ainda não compra."),
    kpi("FV_CREDITO", "Crédito disponível na carteira (aprox.)", FV, PF, "credito_disponivel_carteira", origem=O_FV,
        rule="Ion IONVD_CLIENTES_CREDDISP / MaxSoluções PCMXSCLIENTECREDDISP: VLLIMITE − VLTITULOS − VLPEDIDOS − VLCHEQUES + VLCREDITO + VLSAZONAL (PKG_LIMITECREDITO). Aqui sem cheques e sazonal: limite − títulos em aberto − pedidos pendentes.",
        desc="Quanto de crédito a carteira ainda tem para comprar.",
        calc="Para cada cliente com limite, subtrai do limite o que está em aberto e os pedidos pendentes; soma o que sobra.",
        why="É a mesma conta que trava o pedido no app do vendedor. Carteira sem crédito não cresce, por melhor que seja a visita."),
    kpi("FV_SEM_CREDITO", "Clientes sem crédito disponível", FV, PC, "clientes_sem_credito_pct", origem=O_FV,
        rule="Clientes com limite cujo crédito disponível (mesma conta acima) ≤ 0.",
        desc="Parcela da carteira que não consegue comprar.",
        calc="Dos clientes com limite cadastrado, mostra a % com crédito disponível zerado ou negativo.",
        why="Lista pronta para o financeiro: revisar limite ou cobrar para liberar venda."),
    kpi("FV_POS_DELTA", "Variação de positivados", FV, PC, "clientes_positivados_delta", origem=O_FV,
        rule="Ion CLIENTES_POSITIVADOS_DELTA: positivados no período menos os do período anterior.",
        desc="Se a base positivada cresceu ou encolheu.",
        calc="Clientes positivados no período menos os positivados no período anterior de mesmo tamanho.",
        why="Mostra a tendência antes de o faturamento refletir."),
    kpi("FV_PERDIDOS", "Clientes perdidos no mês", FV, PC, "clientes_perdidos_mes", origem=O_BI,
        rule="GEO F_BI_CLISEMVENDAMES: positivados no mês anterior (PCPEDC) que não têm pedido no mês corrente, por RCA/supervisor.",
        desc="Quem comprou mês passado e sumiu este mês.",
        calc="Lista os clientes que compraram no mês anterior e conta quantos ainda não compraram neste mês.",
        why="É a lista de recuperação mais quente que existe: o cliente acabou de parar. O vendedor liga antes de o concorrente entrar."),
    kpi("FV_RCA_SEM_VENDA", "RCAs ativos sem venda", FV, PP, "rcas_sem_venda", origem=O_BI,
        rule="GEO F_BI_RCASEMVENDA: vendedores ativos (sem DTTERMINO) sem pedido no período.",
        desc="Vendedores cadastrados que não produziram.",
        calc="Conta os vendedores ativos que não tiveram nenhuma nota no período.",
        why="Vendedor sem venda é rota descoberta ou cadastro que deveria estar inativo."),
    kpi("FV_CARTEIRA_POS", "Carteira positivada", FV, PC, "carteira_positivada_pct", origem=O_BI,
        rule="GEO F_BI_CARTEIRA (consulta 100 do SIG): positivados ÷ carteira, onde carteira = clientes do RCA sem DTEXCLUSAO e RCA sem DTTERMINO.",
        desc="Quanto da carteira de cada vendedor comprou.",
        calc="Clientes positivados divididos pelos clientes da carteira (não bloqueados, com vendedor).",
        why="Diferente da cobertura da base ativa: aqui entra a carteira inteira, inclusive quem está parado. É a régua do supervisor."),
    kpi("FV_CARTEIRA_INAT", "Carteira inativa", FV, PC, "carteira_inativa_pct", origem=O_BI,
        rule="GEO F_BI_CARTEIRA.INATIVO: DTULTCOMP anterior a SYSDATE − PCCONSUM.NUMDIASCLIINATIV (90).",
        desc="Parcela da carteira parada.",
        calc="Clientes da carteira sem compra há mais de 90 dias divididos pela carteira.",
        why="Mesma régua que o WinThor usa para chamar um cliente de inativo; é o alvo da reativação."),
    kpi("FV_VISITAS", "Compromissos de visita cumpridos", FV, PC, requer=["PCROTACLI", "IONVD_VENDEDOR_COMPROMISSOS"], origem=O_FV,
        sistema="Força de vendas com agenda de visitas (Ion) ou roteiro de visitas do WinThor (PCROTACLI)",
        rule="Ion IONVD_VENDEDOR_COMPROMISSOS / IONVR_COMPROMISSOS_FINALIZADOS; no WinThor, ATUALIZACAO_DIARIA.P_PC_GERAROTACLI grava PCROTACLI.",
        desc="Visitas planejadas que viraram atendimento.",
        calc="Compara as visitas agendadas para o vendedor com as que tiveram pedido ou registro de visita.",
        why="Visita sem pedido é custo de rota; cliente sem visita é churn.",
        unit="%", polarity="maior_melhor", aggregation="media"),
    kpi("FV_DEVOL_MOTIVO", "Devoluções por motivo", FV, PC, requer=["PCNFENT (TIPODESCARGA 6/7)", "PCTABDEV"], origem=O_FV,
        rule="Ion IONVD_DEVOLUCOES: PCNFENT.TIPODESCARGA 6/7 × PCMOV, motivo em PCTABDEV, ligada à venda por NUMTRANSVENDA; valor = QT × (PUNIT + frete + outras − repasse − ST).",
        desc="Valor devolvido por motivo de devolução.",
        calc="Soma o valor das devoluções do período agrupado pelo motivo registrado no ERP.",
        why="Separa devolução por avaria, erro de pedido ou recusa do cliente: cada uma tem dono diferente.",
        unit="R$", polarity="menor_melhor", aggregation="soma"),

    # --------------------------------------------------------------- ARMAZÉM / WMS
    # Regras do módulo WMS do próprio WinThor (PCMOVENDPEND, WMS_PROCESSACORTE, RF 3723/3734).
    # Só existe se o cliente usa o WMS do WinThor (PCFILIAL.USAWMS = S).
    kpi("WMS_OS", "OS de separação concluídas", WMS, PP, "wms_os_concluidas", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="PCMOVENDPEND agregada por NUMOS: CODOPER S*, DTESTORNO nula, todas as linhas com DTFIMSEPARACAO (a RF 3723 só carimba quando QTSEPARADA = QT).",
        desc="Volume de trabalho do armazém.",
        calc="Conta as ordens de separação de saída concluídas no período.",
        why="Base da produtividade do armazém e do dimensionamento de equipe por turno."),
    kpi("WMS_TEMPO_SEP", "Tempo médio de separação", WMS, PP, "wms_tempo_separacao_min", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="MAX(DTFIMSEPARACAO) − MIN(DTINICIOOS) por OS, ponderado pelas linhas.",
        desc="Quanto tempo uma OS leva para ser separada.",
        calc="Minutos entre o início e o fim da separação de cada OS, ponderados pela quantidade de linhas.",
        why="Tempo de separação subindo é carga saindo mais tarde; olhar por separador e por turno."),
    kpi("WMS_TEMPO_CONF", "Tempo médio de conferência", WMS, PP, "wms_tempo_conferencia_min", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="MAX(DTFIMCONFERENCIA) − MIN(DTINICIOCONFERENCIA) por OS.",
        desc="Quanto tempo a conferência leva.",
        calc="Minutos entre o início e o fim da conferência de cada OS.",
        why="Conferência lenta trava o faturamento da carga (WMS_EXISTPENDENCIASEPWMS bloqueia a rotina 1402)."),
    kpi("WMS_PENDENTES", "OS de saída pendentes", WMS, PP, "wms_os_pendentes", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="OS de saída sem DTFIMSEPARACAO e não canceladas no fim do período.",
        desc="Fila do armazém.",
        calc="Conta as ordens de saída ainda não separadas.",
        why="Fila crescendo é atraso de carga amanhã."),
    kpi("WMS_PRODUTIVIDADE", "Linhas separadas por hora", WMS, PP, "wms_linhas_por_hora", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="Linhas das OS concluídas ÷ horas entre DTINICIOOS e DTFIMSEPARACAO.",
        desc="Produtividade da separação.",
        calc="Linhas separadas divididas pelas horas gastas na separação.",
        why="Permite meta por separador e comparação entre turnos e filiais."),
    kpi("WMS_CORTE", "Corte na separação", WMS, PC, "wms_corte_pct", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="Σ QTCANCEL ÷ Σ QT nas OS (WMS_PROCESSACORTE grava o corte e devolve reserva e flex).",
        desc="Quanto do pedido o armazém não conseguiu separar.",
        calc="Quantidade cortada dividida pela quantidade pedida nas ordens de separação.",
        why="Corte no WMS com estoque no sistema é endereço errado ou saldo furado; sem estoque é compra."),
    kpi("WMS_ERROS", "Erros de conferência", WMS, PP, "wms_erros_conferencia", origem=O_WMS, sistema="Módulo WMS do WinThor (PCMOVENDPEND)",
        rule="Σ PCMOVENDPEND.QTERROS nas OS do período.",
        desc="Divergências apontadas na conferência.",
        calc="Soma os erros registrados pelos conferentes nas ordens do período.",
        why="Erro pego na conferência é devolução evitada; erro que passa vira ocorrência de entrega."),

    # ---------------------------------------------------- ROTEIRIZAÇÃO / ENTREGA (FusionTrak)
    # Lê o schema FUSIONT do FusionTrak (cargas enviadas ao roteirizador e eventos da rua).
    kpi("ROTA_PCT", "Cargas roteirizadas", ROTA, PP, "cargas_roteirizadas_pct", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT)",
        rule="FUSIONT.FUSIONTRAK_CARGAS_ROTEIRIZADAS (NUMCAR, DTROTEIRIZACAO) sobre PCCARREG expedidas.",
        desc="Quanto da expedição passa pelo roteirizador.",
        calc="Cargas com roteirização registrada divididas pelas cargas expedidas.",
        why="Carga fora do roteirizador é rota montada na mão: mais km e menos previsibilidade."),
    kpi("ROTA_OCUPACAO", "Ocupação do veículo (peso)", ROTA, PP, "ocupacao_peso_pct", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT)",
        rule="FUSIONTRAK_INT_CARGA.PESO ÷ T06_PESO_MAX_ENTREGAS (capacidade do veículo).",
        desc="Aproveitamento da capacidade do veículo.",
        calc="Peso carregado dividido pelo peso máximo do veículo, nas cargas roteirizadas.",
        why="Ocupação baixa é frete caro por quilo; alta demais é risco de excesso de peso."),
    kpi("ROTA_ENTREGAS", "Entregas por carga roteirizada", ROTA, PP, "entregas_por_carga_roteirizada", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT)",
        rule="FUSIONTRAK_INT_CARGA.NUMCLIENTES médio.",
        desc="Densidade de entrega por viagem.",
        calc="Clientes atendidos por carga, em média.",
        why="Mais entregas por carga diluem o custo da viagem."),
    kpi("ROTA_CIDADES", "Cidades por carga", ROTA, PP, "cidades_por_carga", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT)",
        rule="FUSIONTRAK_INT_CARGA.NUMCIDADES médio.",
        desc="Dispersão geográfica da carga.",
        calc="Cidades atendidas por carga, em média.",
        why="Carga espalhada por muitas cidades roda mais km por entrega."),
    kpi("ROTA_OCORR", "Ocorrências de entrega", ROTA, PC, "ocorrencias_entrega", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT, FUSIONTRAK_INT_EVENTOS)",
        rule="FUSIONTRAK_INT_EVENTOS com MOTIVO_DEVOL_REENT_ID; só TIPO = 7 produz efeito no ERP (linha em PCMENS).",
        desc="Problemas registrados na rua.",
        calc="Conta os eventos de entrega com motivo de devolução ou reentrega no período.",
        why="Cada ocorrência é uma reentrega: custo dobrado e cliente insatisfeito."),
    kpi("ROTA_OCORR_PCT", "Entregas com ocorrência", ROTA, PC, "entregas_com_ocorrencia_pct", origem=O_ROTA, sistema="FusionTrak (schema FUSIONT, FUSIONTRAK_INT_EVENTOS)",
        rule="Pedidos com evento de ocorrência ÷ pedidos com evento de entrega.",
        desc="Taxa de entrega com problema.",
        calc="Pedidos com ocorrência divididos pelos pedidos entregues no período.",
        why="É o nível de serviço visto pelo cliente."),
]

# KPIs cuja régua não existe pronta no WinThor: são composição nossa sobre os
# dados do ERP (razões, concentrações, prazos ponderados). Os demais sem
# `origem` explícita reproduzem uma regra que o próprio ERP executa.
COMPOSICAO_TECHSYS = {
    "FAT_YOY", "VENDA_RCA", "POS_RCA", "FREQ", "ITENS_NOTA", "TOP10_CLI", "TOP_RCA", "PRECO_MEDIO",
    "COBERTURA", "RECOMPRA", "INATIVOS", "CHURN", "ATIVOS", "CADASTROS",
    "MARKUP", "LUCRO", "DESP_PCT", "RESULT", "RESULT_PCT", "CR60", "DSO", "NOPRAZO", "ATRASO", "PMR", "PMP",
    "LIQ", "CR30", "CP30", "CP_VENC_PCT", "ENTR_CX", "SAIDA_CX", "GERCX",
    "CAP_PARADO", "CAP_PARADO_PCT", "SEM_GIRO", "EXCESSO", "ABAIXO_MIN", "SKUS", "BLOQ_EST",
    "NF_ENT", "FORN_ATIVOS", "COMPRA_MEDIA", "COMPRAS_PCT", "TOP5_FORN", "FRETE_COMPRA",
    "VL_CARGA", "KG_CARGA", "ROTA_DIAS", "EM_ROTA", "CARGA_CANC", "FRETE_KG", "FRETE_NOTA", "FAT_DIA",
    "NF_DIA", "TRIB", "ICMS", "ST", "IPI", "CASA", "FAT_FUNC", "ADM", "MOTORISTAS",
}
for _item in CATALOGO:
    if _item["code"] in COMPOSICAO_TECHSYS and _item["origin"] == O_WINTHOR:
        _item["origin"] = O_TECHSYS
