# Generated by Django 5.1.15 on 2026-09-17 19:11

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_vinculo_com_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, verbose_name='número')),
                ('description', models.CharField(max_length=250, verbose_name='descrição')),
                ('reference', models.DateField(help_text='Primeiro dia do mês de referência', verbose_name='competência')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='pago em')),
                ('payment_url', models.URLField(blank=True, verbose_name='link de pagamento')),
                ('file', models.FileField(blank=True, max_length=200, null=True, upload_to=billing.models.caminho, verbose_name='PDF / boleto')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_invoice_number')],
            },
        ),
    ]
