# Generated by Django 5.1.15 on 2026-09-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_perfis_de_acesso'),
        ('strategy', '0004_swot_matriz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField(verbose_name='código')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(verbose_name='fim')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='strategy.strategicmap', verbose_name='planejamento')),
                ('objectives', models.ManyToManyField(blank=True, related_name='projects', to='strategy.strategicobjective')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.orgunit', verbose_name='departamento')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owned', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('partners', models.ManyToManyField(blank=True, related_name='projects_partner', to=settings.AUTH_USER_MODEL, verbose_name='parceiros')),
                ('swot_items', models.ManyToManyField(blank=True, related_name='projects', to='strategy.swotitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('phase', models.CharField(choices=[('iniciacao', 'Iniciação'), ('planejamento', 'Planejamento'), ('execucao', 'Execução'), ('monitoramento', 'Monitoramento'), ('encerramento', 'Encerramento')], default='iniciacao', max_length=20, verbose_name='fase')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, verbose_name='% andamento')),
                ('notes', models.TextField(blank=True, verbose_name='registros')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(verbose_name='fato')),
                ('cause', models.TextField(blank=True, verbose_name='causa')),
                ('action', models.TextField(blank=True, verbose_name='ação')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_fcas', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcas', to='projects.projectactivity')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_project_code'),
        ),
    ]
