# Generated by Django 5.1.15 on 2026-09-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('kind', models.CharField(blank=True, max_length=4)),
                ('sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sales_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('mix', models.IntegerField(blank=True, null=True)),
                ('positivation', models.IntegerField(blank=True, null=True)),
                ('positivation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('avg_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('active_customers', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets', to='erp.branch')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets', to='erp.salesrep')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'period'], name='erp_salesta_tenant__a012da_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_sales_target_ext')],
            },
        ),
    ]
