# Generated by Django 5.1.15 on 2026-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_salestarget_active_customers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp', models.CharField(db_index=True, default='winthor', max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('vendas', 'Vendas'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque'), ('compras', 'Compras'), ('logistica', 'Logística'), ('fiscal', 'Fiscal'), ('rh', 'Pessoas / RH'), ('diretoria', 'Diretoria')], max_length=20)),
                ('perspective', models.CharField(choices=[('financeira', 'Financeira'), ('clientes', 'Clientes'), ('processos', 'Processos internos'), ('aprendizado', 'Aprendizado e crescimento')], default='processos', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('polarity', models.CharField(default='maior_melhor', max_length=20)),
                ('aggregation', models.CharField(default='soma', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rule', models.TextField(blank=True)),
                ('erp_metric', models.CharField(blank=True, max_length=60)),
                ('erp_target', models.CharField(blank=True, max_length=40)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('requer', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pronto', 'Pronto (calculado do espelho)'), ('planejado', 'Planejado (depende de coleta adicional)')], default='pronto', max_length=12)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sector', 'order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('erp', 'code'), name='uniq_kpi_template_erp_code')],
            },
        ),
    ]
