# Generated by Django 5.1.15 on 2026-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_kpitemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplate',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpitemplate',
            name='importance',
            field=models.TextField(blank=True),
        ),
    ]
