# Generated by Django 5.1.15 on 2026-09-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('erp', '0005_kpitemplate_explanation_kpitemplate_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplate',
            name='origin',
            field=models.CharField(choices=[('winthor', 'Regra do próprio WinThor'), ('forca_vendas', 'Aprendida da força de vendas (Ion / MaxSoluções)'), ('wms', 'Módulo WMS do WinThor'), ('roteirizador', 'Roteirizador (FusionTrak)'), ('techsys', 'Composição TechSys sobre dados do ERP')], default='winthor', max_length=20),
        ),
        migrations.AddField(
            model_name='kpitemplate',
            name='requires_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='kpitemplate',
            name='sector',
            field=models.CharField(choices=[('vendas', 'Vendas'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque'), ('compras', 'Compras'), ('logistica', 'Logística'), ('fiscal', 'Fiscal'), ('rh', 'Pessoas / RH'), ('forca_vendas', 'Força de vendas'), ('wms', 'Armazém / WMS'), ('roteirizacao', 'Roteirização / entrega'), ('diretoria', 'Diretoria')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, max_length=10)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=30)),
                ('load_number', models.CharField(blank=True, max_length=30)),
                ('driver_code', models.CharField(blank=True, max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=12)),
                ('km', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30)),
                ('longitude', models.CharField(blank=True, max_length=30)),
                ('reason_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='erp_deliver_tenant__48437f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_delivery_event_ext')],
            },
        ),
        migrations.CreateModel(
            name='RouteLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('load_number', models.CharField(blank=True, max_length=30)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('routed_at', models.DateField(blank=True, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=20)),
                ('driver_code', models.CharField(blank=True, max_length=20)),
                ('route', models.CharField(blank=True, max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('num_items', models.IntegerField(blank=True, null=True)),
                ('num_customers', models.IntegerField(blank=True, null=True)),
                ('num_cities', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_loads', to='erp.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'departure_date'], name='erp_routelo_tenant__058fd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_route_load_ext')],
            },
        ),
        migrations.CreateModel(
            name='WmsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('os_type', models.CharField(blank=True, max_length=6)),
                ('operation', models.CharField(blank=True, max_length=4)),
                ('order_number', models.CharField(blank=True, max_length=30)),
                ('load_number', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=2)),
                ('lines', models.IntegerField(default=0)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('qty_picked', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('qty_checked', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('qty_canceled', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('errors', models.IntegerField(default=0)),
                ('picking_start', models.DateTimeField(blank=True, null=True)),
                ('picking_end', models.DateTimeField(blank=True, null=True)),
                ('check_start', models.DateTimeField(blank=True, null=True)),
                ('check_end', models.DateTimeField(blank=True, null=True)),
                ('picker', models.CharField(blank=True, max_length=20)),
                ('checker', models.CharField(blank=True, max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_orders', to='erp.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='erp_wmsorde_tenant__e7eb14_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_wms_order_ext')],
            },
        ),
    ]
