# Generated by Django 5.1.15 on 2026-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_kpitemplate_origin_kpitemplate_requires_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryload',
            name='km_end',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryload',
            name='km_start',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryload',
            name='num_cities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryload',
            name='num_customers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
