# Generated by Django 5.1.15 on 2026-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_deliveryload_km_end_deliveryload_km_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpitemplate',
            name='origin',
            field=models.CharField(choices=[('winthor', 'Regra do próprio WinThor'), ('forca_vendas', 'Aprendida da força de vendas (Ion / MaxSoluções)'), ('wms', 'Módulo WMS do WinThor'), ('roteirizador', 'Roteirizador (FusionTrak)'), ('bi', 'BI / geomarketing (schema GEO)'), ('techsys', 'Composição TechSys sobre dados do ERP')], default='winthor', max_length=20),
        ),
    ]
