# Generated by Django 5.1.15 on 2026-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_espelho_varredura'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
