# Generated by Django 5.1.15 on 2026-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
