# Generated by Django 5.1.15 on 2026-09-06 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('indicators', '0004_indicator_erp_target'),
        ('strategy', '0002_strategicobjective_pos_x_strategicobjective_pos_y'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicmap',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='propósito'),
        ),
        migrations.CreateModel(
            name='CanvasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.CharField(choices=[('parcerias', 'Parcerias principais'), ('atividades', 'Atividades principais'), ('recursos', 'Recursos principais'), ('proposta', 'Proposta de valor'), ('relacionamento', 'Relacionamento com clientes'), ('canais', 'Canais'), ('segmentos', 'Segmentos de clientes'), ('custos', 'Estrutura de custos'), ('receitas', 'Fontes de receita')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_items', to='strategy.strategicmap')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['block', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('kind', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='empresa/organização')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='papel')),
                ('email', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('influence', models.PositiveSmallIntegerField(default=3, verbose_name='influência')),
                ('interest', models.PositiveSmallIntegerField(default=3, verbose_name='interesse')),
                ('expectations', models.TextField(blank=True, verbose_name='expectativas')),
                ('is_active', models.BooleanField(default=True)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholders', to='accounts.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('kind', models.CharField(choices=[('resultados', 'Reunião de resultados'), ('planejamento', 'Planejamento estratégico'), ('acompanhamento', 'Acompanhamento de planos'), ('diretoria', 'Diretoria'), ('outra', 'Outra')], default='resultados', max_length=20)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=12)),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='local / link')),
                ('agenda', models.TextField(blank=True, verbose_name='pauta')),
                ('minutes', models.TextField(blank=True, verbose_name='ata')),
                ('decisions', models.TextField(blank=True, verbose_name='decisões')),
                ('indicators', models.ManyToManyField(blank=True, related_name='meetings', to='indicators.indicator')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.orgunit')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='meetings', to='strategy.stakeholder')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SwotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadrant', models.CharField(choices=[('S', 'Força'), ('W', 'Fraqueza'), ('O', 'Oportunidade'), ('T', 'Ameaça')], max_length=1)),
                ('text', models.CharField(max_length=300, verbose_name='descrição')),
                ('detail', models.TextField(blank=True)),
                ('impact', models.PositiveSmallIntegerField(default=3, verbose_name='impacto (1–5)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_items', to='strategy.strategicmap')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategy.strategicobjective')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['quadrant', '-impact', 'order', 'id'],
            },
        ),
    ]
