# Generated by Django 5.1.15 on 2026-09-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('strategy', '0003_swot_canvas_stakeholders_reunioes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwotStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SO', 'Forças × Oportunidades (ofensiva)'), ('WO', 'Fraquezas × Oportunidades (reforço)'), ('ST', 'Forças × Ameaças (defesa)'), ('WT', 'Fraquezas × Ameaças (sobrevivência)')], max_length=2)),
                ('text', models.CharField(max_length=300, verbose_name='estratégia')),
                ('order', models.PositiveIntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_strategies', to='strategy.strategicmap')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_strategies', to='strategy.strategicobjective')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
