# Generated by Django 5.1.15 on 2026-09-17 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_em_varias_empresas'),
        ('strategy', '0004_swot_matriz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicmap',
            name='org_units',
            field=models.ManyToManyField(blank=True, related_name='planejamentos', to='accounts.orgunit', verbose_name='departamentos'),
        ),
        migrations.AddField(
            model_name='strategicmap',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='planejamentos', to=settings.AUTH_USER_MODEL, verbose_name='parceiros'),
        ),
        migrations.AddField(
            model_name='strategicmap',
            name='scope',
            field=models.TextField(blank=True, verbose_name='escopo'),
        ),
        migrations.AlterField(
            model_name='strategicmap',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
