# Generated by Django 5.1.15 on 2026-09-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_em_varias_empresas'),
        ('projects', '0001_inicial'),
        ('strategy', '0005_varios_planejamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(default='azul', max_length=10, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='strategy.strategicmap', verbose_name='planejamento'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project'),
        ),
        migrations.CreateModel(
            name='AgendaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='strategy.agendacategory'),
        ),
        migrations.AddConstraint(
            model_name='agendacategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_agenda_category'),
        ),
    ]
