# Generated by Django 5.1.15 on 2026-09-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_agenda_de_trabalho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicmap',
            options={'ordering': ['-year_start', '-id']},
        ),
    ]
