# Generated by Django 5.1.15 on 2026-09-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_modulo_kanban'),
        ('strategy', '0007_ordem_dos_planejamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotitem',
            name='importance',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='importância (1–5)'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='intensity',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='intensidade (1–5)'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='accounts.orgunit', verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='trend',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='tendência (1–5)'),
        ),
    ]
