# Generated by Django 5.1.15 on 2026-09-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('indicators', '0002_initial'),
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('what', models.TextField(blank=True, verbose_name='o quê')),
                ('why', models.TextField(blank=True, verbose_name='por quê')),
                ('where', models.CharField(blank=True, max_length=250, verbose_name='onde')),
                ('when_start', models.DateField(blank=True, null=True, verbose_name='início')),
                ('when_end', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('how', models.TextField(blank=True, verbose_name='como')),
                ('how_much', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='quanto custa')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('pdca_stage', models.CharField(choices=[('plan', 'Plan'), ('do', 'Do'), ('check', 'Check'), ('act', 'Act')], default='plan', max_length=10)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('desvio', 'Desvio')], default='manual', max_length=20)),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='indicators.indicator')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='strategy.strategicobjective')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='accounts.orgunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to=settings.AUTH_USER_MODEL, verbose_name='quem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('fazendo', 'Fazendo'), ('feito', 'Feito')], default='a_fazer', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.actionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_tratamento', 'Em tratamento'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('root_cause', models.TextField(blank=True, verbose_name='análise de causa')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='indicators.indicator')),
                ('indicator_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviation', to='indicators.indicatorvalue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='deviation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='plans.deviation'),
        ),
    ]
