# Generated by Django 5.1.15 on 2026-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='motivo do bloqueio'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('a_fazer', 'A fazer'), ('fazendo', 'Fazendo'), ('bloqueado', 'Bloqueado'), ('feito', 'Feito')], default='a_fazer', max_length=20),
        ),
    ]
