# Generated by Django 5.1.15 on 2026-09-09 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_kanban_bloqueado_prioridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plans.actionitem'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='avanço %'),
        ),
        migrations.CreateModel(
            name='ActionPlanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='andamento')),
                ('progress_pct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='avanço informado %')),
                ('next_action', models.CharField(blank=True, max_length=250, verbose_name='próxima ação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_updates', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='plans.actionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
