# Generated by Django 5.1.15 on 2026-09-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai', '0001_initial'),
        ('indicators', '0002_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='deviation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='plans.deviation'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant'),
        ),
    ]
