# Generated by Django 5.1.15 on 2026-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='kind',
            field=models.CharField(choices=[('analise_indicador', 'Análise de indicador'), ('analise_desvio', 'Análise de desvio'), ('resumo_mensal', 'Resumo mensal'), ('sugestao_mapa', 'Sugestão de mapa estratégico')], max_length=30),
        ),
    ]
