# Generated by Django 5.1.15 on 2026-09-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_perfis_de_acesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(db_index=True, verbose_name='número')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('category', models.CharField(choices=[('suporte', 'Suporte técnico'), ('consultoria', 'Consultoria de gestão'), ('duvida', 'Dúvida de uso'), ('erro', 'Erro no sistema'), ('melhoria', 'Sugestão de melhoria'), ('dados', 'Dados do ERP / indicador')], default='suporte', max_length=20)),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_cliente', 'Aguardando cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('module', models.CharField(blank=True, max_length=40, verbose_name='módulo')),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='avaliação (1–5)')),
                ('rating_comment', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_opened', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, verbose_name='nota interna (só suporte)')),
                ('from_support', models.BooleanField(default=False, verbose_name='resposta do suporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_ticket_number_tenant'),
        ),
    ]
