# Generated by Django 5.1.15 on 2026-09-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_chamados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_pct', models.FloatField(null=True)),
                ('mem_pct', models.FloatField(null=True)),
                ('mem_usada', models.BigIntegerField(null=True)),
                ('disco_pct', models.FloatField(null=True)),
                ('disco_usado', models.BigIntegerField(null=True)),
                ('load_m1', models.FloatField(null=True)),
                ('db_bytes', models.BigIntegerField(null=True)),
                ('db_conexoes', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
