# Generated by Django 5.1.15 on 2026-09-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='período')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='meta')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='período')),
                ('value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='valor')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('sql', 'SQL'), ('agent', 'Agente')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('achievement_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('sem_meta', 'Sem meta')], default='sem_meta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('api', 'API REST'), ('sql', 'SQL'), ('agent', 'Agente ERP')], default='manual', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unidade')),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('frequency', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('polarity', models.CharField(choices=[('maior_melhor', 'Maior é melhor'), ('menor_melhor', 'Menor é melhor')], default='maior_melhor', max_length=20)),
                ('aggregation', models.CharField(choices=[('soma', 'Soma'), ('media', 'Média'), ('ultimo', 'Último valor')], default='soma', max_length=20)),
                ('yellow_threshold_pct', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='indicators.datasource')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
