# Generated by Django 5.1.15 on 2026-09-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('indicators', '0001_initial'),
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='strategy.strategicobjective'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='accounts.orgunit'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='indicatortarget',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_values', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_indicator_code_tenant'),
        ),
        migrations.AddConstraint(
            model_name='indicatortarget',
            constraint=models.UniqueConstraint(fields=('indicator', 'period'), name='uniq_target_period'),
        ),
        migrations.AddConstraint(
            model_name='indicatorvalue',
            constraint=models.UniqueConstraint(fields=('indicator', 'period'), name='uniq_value_period'),
        ),
    ]
