# Generated by Django 5.1.15 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='erp_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='indicator',
            name='erp_metric',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='métrica do ERP'),
        ),
    ]
