# Generated by Django 5.1.15 on 2026-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicator_erp_filters_indicator_erp_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='erp_target',
            field=models.CharField(blank=True, max_length=40, verbose_name='meta do ERP'),
        ),
    ]
