# Generated by Django 5.1.15 on 2026-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_indicator_erp_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='setor'),
        ),
    ]
